package dominorule

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"strconv"
	"strings"
	"time"

	"github.com/matthewmueller/domino/pgdomino/internal/pogo"
)

// GENERATED BY POGO. DO NOT EDIT.

// ErrDominoRuleNotFound returned if the "public"."domino_rules" is not found
var ErrDominoRuleNotFound = errors.New("dominoRule not found")

// DominoRule result data for "public"."domino_rules"
type DominoRule struct {
	CreatedAt time.Time `json:"created_at,omitempty"`
	ID        int64     `json:"id,omitempty"`
	Name      string    `json:"name,omitempty"`
	Owner     string    `json:"owner,omitempty"`
	Trigger   string    `json:"trigger,omitempty"`
	UpdatedAt time.Time `json:"updated_at,omitempty"`
}

var _ pogo.Row = (*DominoRule)(nil)

// Decode implements pogo.Row
func (dr *DominoRule) Decode(dominoRule interface{}) error {
	_dominoRule, ok := dominoRule.(*DominoRule)
	if !ok {
		return fmt.Errorf(`dominoRule decode: "%T" is not a "*DominoRule"`, dominoRule)
	}
	*_dominoRule = *dr
	return nil
}

// New "public"."domino_rules" input
func New() *Input {
	return &Input{}
}

// Input data for "public"."domino_rules"
type Input struct {
	createdAt *time.Time
	id        *int64
	name      *string
	owner     *string
	trigger   *string
	updatedAt *time.Time
}

var _ pogo.Insertable = (*Input)(nil)

// CreatedAt sets the created_at
func (dr *Input) CreatedAt(createdAt time.Time) *Input {
	dr.createdAt = &createdAt
	return dr
}

// ID sets the id
func (dr *Input) ID(id int64) *Input {
	dr.id = &id
	return dr
}

// Name sets the name
func (dr *Input) Name(name string) *Input {
	dr.name = &name
	return dr
}

// Owner sets the owner
func (dr *Input) Owner(owner string) *Input {
	dr.owner = &owner
	return dr
}

// Trigger sets the trigger
func (dr *Input) Trigger(trigger string) *Input {
	dr.trigger = &trigger
	return dr
}

// UpdatedAt sets the updated_at
func (dr *Input) UpdatedAt(updatedAt time.Time) *Input {
	dr.updatedAt = &updatedAt
	return dr
}

// MarshalJSON marshals the "dominoRule" into JSON
func (dr *Input) MarshalJSON() ([]byte, error) {
	return json.Marshal(dr)
}

// UnmarshalJSON unmarshals json to a "dominoRule"
func (dr *Input) UnmarshalJSON(data []byte) error {
	return json.Unmarshal(data, dr)
}

// String of the input
// TODO: make this more useful
func (dr *Input) String() string {
	return `"public"."domino_rules"`
}

func (dr *Input) columns() map[string]interface{} {
	columns := make(map[string]interface{})

	if dr.createdAt != nil {
		columns["created_at"] = *dr.createdAt
	}

	if dr.id != nil {
		columns["id"] = *dr.id
	}

	if dr.name != nil {
		columns["name"] = *dr.name
	}

	if dr.owner != nil {
		columns["owner"] = *dr.owner
	}

	if dr.trigger != nil {
		columns["trigger"] = *dr.trigger
	}

	if dr.updatedAt != nil {
		columns["updated_at"] = *dr.updatedAt
	}

	return columns
}

// Insert implements pogo.Insertable
func (dr *Input) Insert(db pogo.DB) (pogo.Row, error) {
	return Insert(db, dr)
}

// NewFilter creates a new filter
func NewFilter() *Filter {
	return &Filter{}
}

// Filter filters for "public"."domino_rules"
type Filter struct {
	formats []string
	values  []interface{}
	error   error
}

var _ pogo.Condition = (*Filter)(nil)

// Clause fn
func (f *Filter) Clause() *pogo.Clause {
	return &pogo.Clause{
		Type:   "WHERE",
		Format: strings.Join(f.formats, " AND "),
		Params: f.values,
		Error:  f.error,
	}
}

// And filter
// func (f *Filter) And(filters ...*Filter) *Filter {
//   var clauses []string
//   for _, filter := range filters {
//     _ = filter
//     // clauses = append(clauses, string(filter.Condition()))
//   }
//   f.clauses = append(f.clauses, strings.Join(clauses, " AND "))
//   return f
// }

// Or filter
// func (f *Filter) Or(filters ...*Filter) *Filter {
//   var clauses []string
//   for _, filter := range filters {
//     _ = filter
//     // clauses = append(clauses, string(filter.Condition()))
//   }
//   f.clauses = append(f.clauses, strings.Join(clauses, " OR "))
//   return f
// }

// CreatedAt created_at is equal to
func (f *Filter) CreatedAt(v time.Time) *Filter {
	f.formats = append(f.formats, `"created_at" = %s`)
	f.values = append(f.values, v.Format("2006-01-02 15:04:05.999999999Z07:00"))
	return f
}

// CreatedAtNot created_at is not equal to
func (f *Filter) CreatedAtNot(v time.Time) *Filter {
	f.formats = append(f.formats, `"created_at" != %s`)
	f.values = append(f.values, v.Format("2006-01-02 15:04:05.999999999Z07:00"))
	return f
}

// CreatedAtIn created_at is in
func (f *Filter) CreatedAtIn(v ...time.Time) *Filter {
	var rs []string
	if len(v) == 0 {
		f.formats = append(f.formats, `false`)
		return f
	}
	for range v {
		rs = append(rs, "%s")
	}
	f.formats = append(f.formats, fmt.Sprintf(`"created_at" IN (%s)`, strings.Join(rs, `, `)))
	for _, i := range v {
		f.values = append(f.values, i.Format("2006-01-02 15:04:05.999999999Z07:00"))
	}
	return f
}

// CreatedAtNotIn created_at is not in
func (f *Filter) CreatedAtNotIn(v ...time.Time) *Filter {
	var rs []string
	if len(v) == 0 {
		f.formats = append(f.formats, `false`)
		return f
	}
	for range v {
		rs = append(rs, "%s")
	}
	f.formats = append(f.formats, fmt.Sprintf(`"created_at" NOT IN (%s)`, strings.Join(rs, `, `)))
	for _, i := range v {
		f.values = append(f.values, i.Format("2006-01-02 15:04:05.999999999Z07:00"))
	}
	return f
}

// CreatedAtLt created_at is less than
func (f *Filter) CreatedAtLt(v time.Time) *Filter {
	f.formats = append(f.formats, `"created_at" < %s`)
	f.values = append(f.values, v.Format("2006-01-02 15:04:05.999999999Z07:00"))
	return f
}

// CreatedAtLte created_at is less than or equal
func (f *Filter) CreatedAtLte(v time.Time) *Filter {
	f.formats = append(f.formats, `"created_at" <= %s`)
	f.values = append(f.values, v.Format("2006-01-02 15:04:05.999999999Z07:00"))
	return f
}

// CreatedAtGt created_at is greater than
func (f *Filter) CreatedAtGt(v time.Time) *Filter {
	f.formats = append(f.formats, `"created_at" > %s`)
	f.values = append(f.values, v.Format("2006-01-02 15:04:05.999999999Z07:00"))
	return f
}

// CreatedAtGte created_at is greater than or equal
func (f *Filter) CreatedAtGte(v time.Time) *Filter {
	f.formats = append(f.formats, `"created_at" >= %s`)
	f.values = append(f.values, v.Format("2006-01-02 15:04:05.999999999Z07:00"))
	return f
}

// ID id equals
func (f *Filter) ID(v int64) *Filter {
	f.formats = append(f.formats, `"id" = %s`)
	f.values = append(f.values, v)
	return f
}

// IDNot id doesn't equal
func (f *Filter) IDNot(v int64) *Filter {
	f.formats = append(f.formats, `"id" != %s`)
	f.values = append(f.values, v)
	return f
}

// IDLt id is less than
func (f *Filter) IDLt(v int64) *Filter {
	f.formats = append(f.formats, `"id" < %s`)
	f.values = append(f.values, v)
	return f
}

// IDLte id is less than or equal
func (f *Filter) IDLte(v int64) *Filter {
	f.formats = append(f.formats, `"id" <= %s`)
	f.values = append(f.values, v)
	return f
}

// IDGt id is greater than
func (f *Filter) IDGt(v int64) *Filter {
	f.formats = append(f.formats, `"id" > %s`)
	f.values = append(f.values, v)
	return f
}

// IDGte id is greater than or equal
func (f *Filter) IDGte(v int64) *Filter {
	f.formats = append(f.formats, `"id" >= %s`)
	f.values = append(f.values, v)
	return f
}

// IDIn id is in
func (f *Filter) IDIn(v ...int64) *Filter {
	var rs []string
	if len(v) == 0 {
		f.formats = append(f.formats, `false`)
		return f
	}
	for range v {
		rs = append(rs, "%s")
	}
	f.formats = append(f.formats, fmt.Sprintf(`"id" IN (%s)`, strings.Join(rs, `, `)))
	for _, i := range v {
		f.values = append(f.values, i)
	}
	return f
}

// IDNotIn id is not in
func (f *Filter) IDNotIn(v ...int64) *Filter {
	var rs []string
	if len(v) == 0 {
		f.formats = append(f.formats, `false`)
		return f
	}
	for range v {
		rs = append(rs, "%s")
	}
	f.formats = append(f.formats, fmt.Sprintf(`"id" NOT IN (%s)`, strings.Join(rs, `, `)))
	for _, i := range v {
		f.values = append(f.values, i)
	}
	return f
}

// Name name equals
func (f *Filter) Name(v string) *Filter {
	f.formats = append(f.formats, `"name" = %s`)
	f.values = append(f.values, v)
	return f
}

// NameNot name doesn't equal
func (f *Filter) NameNot(v string) *Filter {
	f.formats = append(f.formats, `"name" != %s`)
	f.values = append(f.values, v)
	return f
}

// NameContains name contains
func (f *Filter) NameContains(v string) *Filter {
	f.formats = append(f.formats, `"name" LIKE '%%' || %s || '%%'`)
	f.values = append(f.values, v)
	return f
}

// NameNotContains name doesn't contain
func (f *Filter) NameNotContains(v string) *Filter {
	f.formats = append(f.formats, `"name" NOT LIKE '%%' || %s || '%%'`)
	f.values = append(f.values, v)
	return f
}

// NameStartsWith name starts with
func (f *Filter) NameStartsWith(v string) *Filter {
	f.formats = append(f.formats, `"name" LIKE %s || '%%'`)
	f.values = append(f.values, v)
	return f
}

// NameNotStartsWith name doesn't start with
func (f *Filter) NameNotStartsWith(v string) *Filter {
	f.formats = append(f.formats, `"name" NOT LIKE %s || '%%'`)
	f.values = append(f.values, v)
	return f
}

// NameEndsWith name ends with
func (f *Filter) NameEndsWith(v string) *Filter {
	f.formats = append(f.formats, `"name" LIKE '%%' || %s`)
	f.values = append(f.values, v)
	return f
}

// NameNotEndsWith name doesn't end with
func (f *Filter) NameNotEndsWith(v string) *Filter {
	f.formats = append(f.formats, `"name" NOT LIKE '%%' || %s`)
	f.values = append(f.values, v)
	return f
}

// NameLt name is less than
func (f *Filter) NameLt(v string) *Filter {
	f.formats = append(f.formats, `"name" < %s`)
	f.values = append(f.values, v)
	return f
}

// NameLte name is less than or equal
func (f *Filter) NameLte(v string) *Filter {
	f.formats = append(f.formats, `"name" <= %s`)
	f.values = append(f.values, v)
	return f
}

// NameGt name is greater than
func (f *Filter) NameGt(v string) *Filter {
	f.formats = append(f.formats, `"name" > %s`)
	f.values = append(f.values, v)
	return f
}

// NameGte name is greater than or equal
func (f *Filter) NameGte(v string) *Filter {
	f.formats = append(f.formats, `"name" >= %s`)
	f.values = append(f.values, v)
	return f
}

// NameIn name is in
func (f *Filter) NameIn(v ...string) *Filter {
	var rs []string
	if len(v) == 0 {
		f.formats = append(f.formats, `false`)
		return f
	}
	for range v {
		rs = append(rs, "%s")
	}
	f.formats = append(f.formats, fmt.Sprintf(`"name" IN (%s)`, strings.Join(rs, `, `)))
	for _, i := range v {
		f.values = append(f.values, i)
	}
	return f
}

// NameNotIn name is not in
func (f *Filter) NameNotIn(v ...string) *Filter {
	var rs []string
	if len(v) == 0 {
		f.formats = append(f.formats, `false`)
		return f
	}
	for range v {
		rs = append(rs, "%s")
	}
	f.formats = append(f.formats, fmt.Sprintf(`"name" NOT IN (%s)`, strings.Join(rs, `, `)))
	for _, i := range v {
		f.values = append(f.values, i)
	}
	return f
}

// Owner owner equals
func (f *Filter) Owner(v string) *Filter {
	f.formats = append(f.formats, `"owner" = %s`)
	f.values = append(f.values, v)
	return f
}

// OwnerNot owner doesn't equal
func (f *Filter) OwnerNot(v string) *Filter {
	f.formats = append(f.formats, `"owner" != %s`)
	f.values = append(f.values, v)
	return f
}

// OwnerContains owner contains
func (f *Filter) OwnerContains(v string) *Filter {
	f.formats = append(f.formats, `"owner" LIKE '%%' || %s || '%%'`)
	f.values = append(f.values, v)
	return f
}

// OwnerNotContains owner doesn't contain
func (f *Filter) OwnerNotContains(v string) *Filter {
	f.formats = append(f.formats, `"owner" NOT LIKE '%%' || %s || '%%'`)
	f.values = append(f.values, v)
	return f
}

// OwnerStartsWith owner starts with
func (f *Filter) OwnerStartsWith(v string) *Filter {
	f.formats = append(f.formats, `"owner" LIKE %s || '%%'`)
	f.values = append(f.values, v)
	return f
}

// OwnerNotStartsWith owner doesn't start with
func (f *Filter) OwnerNotStartsWith(v string) *Filter {
	f.formats = append(f.formats, `"owner" NOT LIKE %s || '%%'`)
	f.values = append(f.values, v)
	return f
}

// OwnerEndsWith owner ends with
func (f *Filter) OwnerEndsWith(v string) *Filter {
	f.formats = append(f.formats, `"owner" LIKE '%%' || %s`)
	f.values = append(f.values, v)
	return f
}

// OwnerNotEndsWith owner doesn't end with
func (f *Filter) OwnerNotEndsWith(v string) *Filter {
	f.formats = append(f.formats, `"owner" NOT LIKE '%%' || %s`)
	f.values = append(f.values, v)
	return f
}

// OwnerLt owner is less than
func (f *Filter) OwnerLt(v string) *Filter {
	f.formats = append(f.formats, `"owner" < %s`)
	f.values = append(f.values, v)
	return f
}

// OwnerLte owner is less than or equal
func (f *Filter) OwnerLte(v string) *Filter {
	f.formats = append(f.formats, `"owner" <= %s`)
	f.values = append(f.values, v)
	return f
}

// OwnerGt owner is greater than
func (f *Filter) OwnerGt(v string) *Filter {
	f.formats = append(f.formats, `"owner" > %s`)
	f.values = append(f.values, v)
	return f
}

// OwnerGte owner is greater than or equal
func (f *Filter) OwnerGte(v string) *Filter {
	f.formats = append(f.formats, `"owner" >= %s`)
	f.values = append(f.values, v)
	return f
}

// OwnerIn owner is in
func (f *Filter) OwnerIn(v ...string) *Filter {
	var rs []string
	if len(v) == 0 {
		f.formats = append(f.formats, `false`)
		return f
	}
	for range v {
		rs = append(rs, "%s")
	}
	f.formats = append(f.formats, fmt.Sprintf(`"owner" IN (%s)`, strings.Join(rs, `, `)))
	for _, i := range v {
		f.values = append(f.values, i)
	}
	return f
}

// OwnerNotIn owner is not in
func (f *Filter) OwnerNotIn(v ...string) *Filter {
	var rs []string
	if len(v) == 0 {
		f.formats = append(f.formats, `false`)
		return f
	}
	for range v {
		rs = append(rs, "%s")
	}
	f.formats = append(f.formats, fmt.Sprintf(`"owner" NOT IN (%s)`, strings.Join(rs, `, `)))
	for _, i := range v {
		f.values = append(f.values, i)
	}
	return f
}

// Trigger trigger equals
func (f *Filter) Trigger(v string) *Filter {
	f.formats = append(f.formats, `"trigger" = %s`)
	f.values = append(f.values, v)
	return f
}

// TriggerNot trigger doesn't equal
func (f *Filter) TriggerNot(v string) *Filter {
	f.formats = append(f.formats, `"trigger" != %s`)
	f.values = append(f.values, v)
	return f
}

// TriggerContains trigger contains
func (f *Filter) TriggerContains(v string) *Filter {
	f.formats = append(f.formats, `"trigger" LIKE '%%' || %s || '%%'`)
	f.values = append(f.values, v)
	return f
}

// TriggerNotContains trigger doesn't contain
func (f *Filter) TriggerNotContains(v string) *Filter {
	f.formats = append(f.formats, `"trigger" NOT LIKE '%%' || %s || '%%'`)
	f.values = append(f.values, v)
	return f
}

// TriggerStartsWith trigger starts with
func (f *Filter) TriggerStartsWith(v string) *Filter {
	f.formats = append(f.formats, `"trigger" LIKE %s || '%%'`)
	f.values = append(f.values, v)
	return f
}

// TriggerNotStartsWith trigger doesn't start with
func (f *Filter) TriggerNotStartsWith(v string) *Filter {
	f.formats = append(f.formats, `"trigger" NOT LIKE %s || '%%'`)
	f.values = append(f.values, v)
	return f
}

// TriggerEndsWith trigger ends with
func (f *Filter) TriggerEndsWith(v string) *Filter {
	f.formats = append(f.formats, `"trigger" LIKE '%%' || %s`)
	f.values = append(f.values, v)
	return f
}

// TriggerNotEndsWith trigger doesn't end with
func (f *Filter) TriggerNotEndsWith(v string) *Filter {
	f.formats = append(f.formats, `"trigger" NOT LIKE '%%' || %s`)
	f.values = append(f.values, v)
	return f
}

// TriggerLt trigger is less than
func (f *Filter) TriggerLt(v string) *Filter {
	f.formats = append(f.formats, `"trigger" < %s`)
	f.values = append(f.values, v)
	return f
}

// TriggerLte trigger is less than or equal
func (f *Filter) TriggerLte(v string) *Filter {
	f.formats = append(f.formats, `"trigger" <= %s`)
	f.values = append(f.values, v)
	return f
}

// TriggerGt trigger is greater than
func (f *Filter) TriggerGt(v string) *Filter {
	f.formats = append(f.formats, `"trigger" > %s`)
	f.values = append(f.values, v)
	return f
}

// TriggerGte trigger is greater than or equal
func (f *Filter) TriggerGte(v string) *Filter {
	f.formats = append(f.formats, `"trigger" >= %s`)
	f.values = append(f.values, v)
	return f
}

// TriggerIn trigger is in
func (f *Filter) TriggerIn(v ...string) *Filter {
	var rs []string
	if len(v) == 0 {
		f.formats = append(f.formats, `false`)
		return f
	}
	for range v {
		rs = append(rs, "%s")
	}
	f.formats = append(f.formats, fmt.Sprintf(`"trigger" IN (%s)`, strings.Join(rs, `, `)))
	for _, i := range v {
		f.values = append(f.values, i)
	}
	return f
}

// TriggerNotIn trigger is not in
func (f *Filter) TriggerNotIn(v ...string) *Filter {
	var rs []string
	if len(v) == 0 {
		f.formats = append(f.formats, `false`)
		return f
	}
	for range v {
		rs = append(rs, "%s")
	}
	f.formats = append(f.formats, fmt.Sprintf(`"trigger" NOT IN (%s)`, strings.Join(rs, `, `)))
	for _, i := range v {
		f.values = append(f.values, i)
	}
	return f
}

// UpdatedAt updated_at is equal to
func (f *Filter) UpdatedAt(v time.Time) *Filter {
	f.formats = append(f.formats, `"updated_at" = %s`)
	f.values = append(f.values, v.Format("2006-01-02 15:04:05.999999999Z07:00"))
	return f
}

// UpdatedAtNot updated_at is not equal to
func (f *Filter) UpdatedAtNot(v time.Time) *Filter {
	f.formats = append(f.formats, `"updated_at" != %s`)
	f.values = append(f.values, v.Format("2006-01-02 15:04:05.999999999Z07:00"))
	return f
}

// UpdatedAtIn updated_at is in
func (f *Filter) UpdatedAtIn(v ...time.Time) *Filter {
	var rs []string
	if len(v) == 0 {
		f.formats = append(f.formats, `false`)
		return f
	}
	for range v {
		rs = append(rs, "%s")
	}
	f.formats = append(f.formats, fmt.Sprintf(`"updated_at" IN (%s)`, strings.Join(rs, `, `)))
	for _, i := range v {
		f.values = append(f.values, i.Format("2006-01-02 15:04:05.999999999Z07:00"))
	}
	return f
}

// UpdatedAtNotIn updated_at is not in
func (f *Filter) UpdatedAtNotIn(v ...time.Time) *Filter {
	var rs []string
	if len(v) == 0 {
		f.formats = append(f.formats, `false`)
		return f
	}
	for range v {
		rs = append(rs, "%s")
	}
	f.formats = append(f.formats, fmt.Sprintf(`"updated_at" NOT IN (%s)`, strings.Join(rs, `, `)))
	for _, i := range v {
		f.values = append(f.values, i.Format("2006-01-02 15:04:05.999999999Z07:00"))
	}
	return f
}

// UpdatedAtLt updated_at is less than
func (f *Filter) UpdatedAtLt(v time.Time) *Filter {
	f.formats = append(f.formats, `"updated_at" < %s`)
	f.values = append(f.values, v.Format("2006-01-02 15:04:05.999999999Z07:00"))
	return f
}

// UpdatedAtLte updated_at is less than or equal
func (f *Filter) UpdatedAtLte(v time.Time) *Filter {
	f.formats = append(f.formats, `"updated_at" <= %s`)
	f.values = append(f.values, v.Format("2006-01-02 15:04:05.999999999Z07:00"))
	return f
}

// UpdatedAtGt updated_at is greater than
func (f *Filter) UpdatedAtGt(v time.Time) *Filter {
	f.formats = append(f.formats, `"updated_at" > %s`)
	f.values = append(f.values, v.Format("2006-01-02 15:04:05.999999999Z07:00"))
	return f
}

// UpdatedAtGte updated_at is greater than or equal
func (f *Filter) UpdatedAtGte(v time.Time) *Filter {
	f.formats = append(f.formats, `"updated_at" >= %s`)
	f.values = append(f.values, v.Format("2006-01-02 15:04:05.999999999Z07:00"))
	return f
}

// OrderBy specificies the ORDERBy BY <order>
type OrderBy string

const (
	// ASC sorts by ascending order
	ASC OrderBy = "ASC"

	// DESC sorts by descending order
	DESC OrderBy = "DESC"
)

// NewOrder fn
func NewOrder() *Orderer {
	return &Orderer{}
}

var _ pogo.Condition = (*Orderer)(nil)

// Orderer orders the given fields
type Orderer struct {
	formats []string
}

// Clause fn
func (o *Orderer) Clause() *pogo.Clause {
	return &pogo.Clause{
		Type:   "ORDER BY",
		Format: strings.Join(o.formats, ", "),
	}
}

// CreatedAt sorts "created_at" by an expression
func (o *Orderer) CreatedAt(order OrderBy) *Orderer {
	o.formats = append(o.formats, fmt.Sprintf(`"created_at" %s`, order))
	return o
}

// ID sorts "id" by an expression
func (o *Orderer) ID(order OrderBy) *Orderer {
	o.formats = append(o.formats, fmt.Sprintf(`"id" %s`, order))
	return o
}

// Name sorts "name" by an expression
func (o *Orderer) Name(order OrderBy) *Orderer {
	o.formats = append(o.formats, fmt.Sprintf(`"name" %s`, order))
	return o
}

// Owner sorts "owner" by an expression
func (o *Orderer) Owner(order OrderBy) *Orderer {
	o.formats = append(o.formats, fmt.Sprintf(`"owner" %s`, order))
	return o
}

// Trigger sorts "trigger" by an expression
func (o *Orderer) Trigger(order OrderBy) *Orderer {
	o.formats = append(o.formats, fmt.Sprintf(`"trigger" %s`, order))
	return o
}

// UpdatedAt sorts "updated_at" by an expression
func (o *Orderer) UpdatedAt(order OrderBy) *Orderer {
	o.formats = append(o.formats, fmt.Sprintf(`"updated_at" %s`, order))
	return o
}

// Model is an empty struct that has all the methods.
// It's primarly used for embedding the methods
// into higher-level models.
type Model struct{}

// Insert a ""public"."domino_rules"" into the "public"."domino_rules"
func Insert(db pogo.DB, dominoRule *Input) (*DominoRule, error) {
	// get all the non-nil columns and prepare them for the query
	_c, _i, _v := slice(dominoRule.columns(), 0)
	_ = _i

	// sql insert query, primary key provided by sequence
	var sqlstr string
	if len(_c) == 0 {
		sqlstr = `
      INSERT INTO "public"."domino_rules"
      DEFAULT VALUES
      RETURNING "created_at", "id", "name", "owner", "trigger", "updated_at"
    `
	} else {
		sqlstr = `
      INSERT INTO "public"."domino_rules" (` + strings.Join(_c, ", ") + `)
      VALUES (` + strings.Join(_i, ", ") + `)
      RETURNING "created_at", "id", "name", "owner", "trigger", "updated_at"
    `
	}

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, _v...)
	}

	var _dominoRule DominoRule
	row := db.QueryRow(context.TODO(), sqlstr, _v...)
	if e := row.Scan(&_dominoRule.CreatedAt, &_dominoRule.ID, &_dominoRule.Name, &_dominoRule.Owner, &_dominoRule.Trigger, &_dominoRule.UpdatedAt); e != nil {
		return nil, e
	}

	return &_dominoRule, nil
}

// Insert a ""public"."domino_rules"" into the "public"."domino_rules"
func (*Model) Insert(db pogo.DB, dominoRule *Input) (*DominoRule, error) {
	// get all the non-nil columns and prepare them for the query
	_c, _i, _v := slice(dominoRule.columns(), 0)
	_ = _i

	// sql insert query, primary key provided by sequence
	var sqlstr string
	if len(_c) == 0 {
		sqlstr = `
      INSERT INTO "public"."domino_rules"
      DEFAULT VALUES
      RETURNING "created_at", "id", "name", "owner", "trigger", "updated_at"
    `
	} else {
		sqlstr = `
      INSERT INTO "public"."domino_rules" (` + strings.Join(_c, ", ") + `)
      VALUES (` + strings.Join(_i, ", ") + `)
      RETURNING "created_at", "id", "name", "owner", "trigger", "updated_at"
    `
	}

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, _v...)
	}

	var _dominoRule DominoRule
	row := db.QueryRow(context.TODO(), sqlstr, _v...)
	if e := row.Scan(&_dominoRule.CreatedAt, &_dominoRule.ID, &_dominoRule.Name, &_dominoRule.Owner, &_dominoRule.Trigger, &_dominoRule.UpdatedAt); e != nil {
		return nil, e
	}

	return &_dominoRule, nil
}

// InsertMany ""public"."domino_rules"" into the "public"."domino_rules"
func InsertMany(db pogo.DB, dominosRules ...*Input) ([]*DominoRule, error) {
	_dominosRules := []*DominoRule{}
	for _, dominoRule := range dominosRules {
		_dominoRule, err := Insert(db, dominoRule)
		if err != nil {
			return _dominosRules, err
		}
		_dominosRules = append(_dominosRules, _dominoRule)
	}
	return _dominosRules, nil
}

// InsertMany ""public"."domino_rules"" into the "public"."domino_rules"
func (*Model) InsertMany(db pogo.DB, dominosRules ...*Input) ([]*DominoRule, error) {
	_dominosRules := []*DominoRule{}
	for _, dominoRule := range dominosRules {
		_dominoRule, err := Insert(db, dominoRule)
		if err != nil {
			return _dominosRules, err
		}
		_dominosRules = append(_dominosRules, _dominoRule)
	}
	return _dominosRules, nil
}

// Find a `DominoRule` by some conditions.
func Find(db pogo.DB, conds ...pogo.Condition) (*DominoRule, error) {
	_s, _v, err := pogo.Conditions(conds...)
	if err != nil {
		return nil, err
	}

	// sql select query, primary key provided by sequence
	sqlstr := `SELECT "created_at", "id", "name", "owner", "trigger", "updated_at" ` +
		`FROM "public"."domino_rules" ` +
		_s

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, _v...)
	}

	var _dominoRule DominoRule
	row := db.QueryRow(context.TODO(), sqlstr, _v...)
	if e := row.Scan(&_dominoRule.CreatedAt, &_dominoRule.ID, &_dominoRule.Name, &_dominoRule.Owner, &_dominoRule.Trigger, &_dominoRule.UpdatedAt); e != nil {
		if pogo.IsNoRows(e) {
			return nil, ErrDominoRuleNotFound
		}
		return nil, e
	}

	return &_dominoRule, nil
}

// Find a `DominoRule` by some conditions.
func (*Model) Find(db pogo.DB, conds ...pogo.Condition) (*DominoRule, error) {
	_s, _v, err := pogo.Conditions(conds...)
	if err != nil {
		return nil, err
	}

	// sql select query, primary key provided by sequence
	sqlstr := `SELECT "created_at", "id", "name", "owner", "trigger", "updated_at" ` +
		`FROM "public"."domino_rules" ` +
		_s

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, _v...)
	}

	var _dominoRule DominoRule
	row := db.QueryRow(context.TODO(), sqlstr, _v...)
	if e := row.Scan(&_dominoRule.CreatedAt, &_dominoRule.ID, &_dominoRule.Name, &_dominoRule.Owner, &_dominoRule.Trigger, &_dominoRule.UpdatedAt); e != nil {
		if pogo.IsNoRows(e) {
			return nil, ErrDominoRuleNotFound
		}
		return nil, e
	}

	return &_dominoRule, nil
}

// FindByID a `DominoRule` by some conditions.
func FindByID(db pogo.DB, id int64) (*DominoRule, error) {
	// sql select query, primary key provided by sequence
	sqlstr := `
    SELECT "created_at", "id", "name", "owner", "trigger", "updated_at"
    FROM "public"."domino_rules"
    WHERE "id" = $1
  `

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, id)
	}

	var _dominoRule DominoRule
	row := db.QueryRow(context.TODO(), sqlstr, id)
	if e := row.Scan(&_dominoRule.CreatedAt, &_dominoRule.ID, &_dominoRule.Name, &_dominoRule.Owner, &_dominoRule.Trigger, &_dominoRule.UpdatedAt); e != nil {
		if pogo.IsNoRows(e) {
			return nil, ErrDominoRuleNotFound
		}
		return nil, e
	}

	return &_dominoRule, nil
}

// FindByID a `DominoRule` by some conditions.
func (*Model) FindByID(db pogo.DB, id int64) (*DominoRule, error) {
	// sql select query, primary key provided by sequence
	sqlstr := `
    SELECT "created_at", "id", "name", "owner", "trigger", "updated_at"
    FROM "public"."domino_rules"
    WHERE "id" = $1
  `

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, id)
	}

	var _dominoRule DominoRule
	row := db.QueryRow(context.TODO(), sqlstr, id)
	if e := row.Scan(&_dominoRule.CreatedAt, &_dominoRule.ID, &_dominoRule.Name, &_dominoRule.Owner, &_dominoRule.Trigger, &_dominoRule.UpdatedAt); e != nil {
		if pogo.IsNoRows(e) {
			return nil, ErrDominoRuleNotFound
		}
		return nil, e
	}

	return &_dominoRule, nil
}

// FindMany finds many "public"."domino_rules" by a condition
func FindMany(db pogo.DB, conds ...pogo.Condition) ([]*DominoRule, error) {
	dominosRules := []*DominoRule{}

	_s, _v, err := pogo.Conditions(conds...)
	if err != nil {
		return dominosRules, err
	}

	// sql select query, primary key provided by sequence
	sqlstr := `SELECT "created_at", "id", "name", "owner", "trigger", "updated_at" ` +
		`FROM "public"."domino_rules" ` +
		_s

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, _v...)
	}

	rows, err := db.Query(context.TODO(), sqlstr, _v...)
	if err != nil {
		return dominosRules, err
	}
	defer rows.Close()

	for rows.Next() {
		var _dominoRule DominoRule
		if e := rows.Scan(&_dominoRule.CreatedAt, &_dominoRule.ID, &_dominoRule.Name, &_dominoRule.Owner, &_dominoRule.Trigger, &_dominoRule.UpdatedAt); e != nil {
			if pogo.IsNoRows(e) {
				return dominosRules, ErrDominoRuleNotFound
			}
			return dominosRules, err
		}
		dominosRules = append(dominosRules, &_dominoRule)
	}
	if rows.Err() != nil {
		return dominosRules, rows.Err()
	}

	return dominosRules, nil
}

// FindMany finds many "public"."domino_rules" by a condition
func (*Model) FindMany(db pogo.DB, conds ...pogo.Condition) ([]*DominoRule, error) {
	dominosRules := []*DominoRule{}

	_s, _v, err := pogo.Conditions(conds...)
	if err != nil {
		return dominosRules, err
	}

	// sql select query, primary key provided by sequence
	sqlstr := `SELECT "created_at", "id", "name", "owner", "trigger", "updated_at" ` +
		`FROM "public"."domino_rules" ` +
		_s

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, _v...)
	}

	rows, err := db.Query(context.TODO(), sqlstr, _v...)
	if err != nil {
		return dominosRules, err
	}
	defer rows.Close()

	for rows.Next() {
		var _dominoRule DominoRule
		if e := rows.Scan(&_dominoRule.CreatedAt, &_dominoRule.ID, &_dominoRule.Name, &_dominoRule.Owner, &_dominoRule.Trigger, &_dominoRule.UpdatedAt); e != nil {
			if pogo.IsNoRows(e) {
				return dominosRules, ErrDominoRuleNotFound
			}
			return dominosRules, err
		}
		dominosRules = append(dominosRules, &_dominoRule)
	}
	if rows.Err() != nil {
		return dominosRules, rows.Err()
	}

	return dominosRules, nil
}

// Update ""public"."domino_rules"" rows in "public"."domino_rules" by a condition, returning 1 result
func Update(db pogo.DB, dominoRule *Input, conds ...pogo.Condition) (*DominoRule, error) {
	_s, _v, err := pogo.Conditions(conds...)
	if err != nil {
		return nil, err
	}

	fields := dominoRule.columns()

	// prepare the slices
	_c, _i, _v2 := slice(fields, len(_v))
	_v = append(_v, _v2...)

	// setup the update fields
	var _u []string
	for i, c := range _c {
		_u = append(_u, c+" = "+_i[i])
	}

	// return an error if no update input is provided
	if len(_u) == 0 {
		return nil, errors.New("dominorule.Update: no input provided")
	}

	// sql query
	sqlstr := `UPDATE "public"."domino_rules" SET ` +
		strings.Join(_u, ", ") + ` ` +
		_s + ` ` +
		`RETURNING "created_at", "id", "name", "owner", "trigger", "updated_at"`

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, _v...)
	}

	// run the query
	var _dominoRule DominoRule
	row := db.QueryRow(context.TODO(), sqlstr, _v...)
	if e := row.Scan(&_dominoRule.CreatedAt, &_dominoRule.ID, &_dominoRule.Name, &_dominoRule.Owner, &_dominoRule.Trigger, &_dominoRule.UpdatedAt); e != nil {
		if pogo.IsNoRows(e) {
			return nil, ErrDominoRuleNotFound
		}
		return nil, e
	}

	return &_dominoRule, nil
}

// Update ""public"."domino_rules"" rows in "public"."domino_rules" by a condition, returning 1 result
func (*Model) Update(db pogo.DB, dominoRule *Input, conds ...pogo.Condition) (*DominoRule, error) {
	_s, _v, err := pogo.Conditions(conds...)
	if err != nil {
		return nil, err
	}

	fields := dominoRule.columns()

	// prepare the slices
	_c, _i, _v2 := slice(fields, len(_v))
	_v = append(_v, _v2...)

	// setup the update fields
	var _u []string
	for i, c := range _c {
		_u = append(_u, c+" = "+_i[i])
	}

	// return an error if no update input is provided
	if len(_u) == 0 {
		return nil, errors.New("dominorule.Update: no input provided")
	}

	// sql query
	sqlstr := `UPDATE "public"."domino_rules" SET ` +
		strings.Join(_u, ", ") + ` ` +
		_s + ` ` +
		`RETURNING "created_at", "id", "name", "owner", "trigger", "updated_at"`

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, _v...)
	}

	// run the query
	var _dominoRule DominoRule
	row := db.QueryRow(context.TODO(), sqlstr, _v...)
	if e := row.Scan(&_dominoRule.CreatedAt, &_dominoRule.ID, &_dominoRule.Name, &_dominoRule.Owner, &_dominoRule.Trigger, &_dominoRule.UpdatedAt); e != nil {
		if pogo.IsNoRows(e) {
			return nil, ErrDominoRuleNotFound
		}
		return nil, e
	}

	return &_dominoRule, nil
}

// UpdateMany updates ""public"."domino_rules"" rows in "public"."domino_rules" by conditions, returning all results
func UpdateMany(db pogo.DB, dominoRule *Input, conds ...pogo.Condition) ([]*DominoRule, error) {
	dominosRules := []*DominoRule{}

	_s, _v, err := pogo.Conditions(conds...)
	if err != nil {
		return nil, err
	}

	fields := dominoRule.columns()

	// prepare the slices
	_c, _i, _v2 := slice(fields, len(_v))
	_v = append(_v, _v2...)

	// setup the update fields
	var _u []string
	for i, c := range _c {
		_u = append(_u, c+" = "+_i[i])
	}

	// return an error if no update input is provided
	if len(_u) == 0 {
		return nil, errors.New("dominorule.UpdateMany: no input provided")
	}

	// sql query
	sqlstr := `UPDATE "public"."domino_rules" SET ` +
		strings.Join(_u, ", ") + ` ` +
		_s + ` ` +
		`RETURNING "created_at", "id", "name", "owner", "trigger", "updated_at"`

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, _v...)
	}

	rows, err := db.Query(context.TODO(), sqlstr, _v...)
	if err != nil {
		return dominosRules, err
	}
	defer rows.Close()

	for rows.Next() {
		var _dominoRule DominoRule
		if e := rows.Scan(&_dominoRule.CreatedAt, &_dominoRule.ID, &_dominoRule.Name, &_dominoRule.Owner, &_dominoRule.Trigger, &_dominoRule.UpdatedAt); e != nil {
			if pogo.IsNoRows(e) {
				return dominosRules, ErrDominoRuleNotFound
			}
			return dominosRules, err
		}
		dominosRules = append(dominosRules, &_dominoRule)
	}
	if rows.Err() != nil {
		return dominosRules, rows.Err()
	}

	return dominosRules, nil
}

// UpdateMany updates ""public"."domino_rules"" rows in "public"."domino_rules" by conditions, returning all results
func (*Model) UpdateMany(db pogo.DB, dominoRule *Input, conds ...pogo.Condition) ([]*DominoRule, error) {
	dominosRules := []*DominoRule{}

	_s, _v, err := pogo.Conditions(conds...)
	if err != nil {
		return nil, err
	}

	fields := dominoRule.columns()

	// prepare the slices
	_c, _i, _v2 := slice(fields, len(_v))
	_v = append(_v, _v2...)

	// setup the update fields
	var _u []string
	for i, c := range _c {
		_u = append(_u, c+" = "+_i[i])
	}

	// return an error if no update input is provided
	if len(_u) == 0 {
		return nil, errors.New("dominorule.UpdateMany: no input provided")
	}

	// sql query
	sqlstr := `UPDATE "public"."domino_rules" SET ` +
		strings.Join(_u, ", ") + ` ` +
		_s + ` ` +
		`RETURNING "created_at", "id", "name", "owner", "trigger", "updated_at"`

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, _v...)
	}

	rows, err := db.Query(context.TODO(), sqlstr, _v...)
	if err != nil {
		return dominosRules, err
	}
	defer rows.Close()

	for rows.Next() {
		var _dominoRule DominoRule
		if e := rows.Scan(&_dominoRule.CreatedAt, &_dominoRule.ID, &_dominoRule.Name, &_dominoRule.Owner, &_dominoRule.Trigger, &_dominoRule.UpdatedAt); e != nil {
			if pogo.IsNoRows(e) {
				return dominosRules, ErrDominoRuleNotFound
			}
			return dominosRules, err
		}
		dominosRules = append(dominosRules, &_dominoRule)
	}
	if rows.Err() != nil {
		return dominosRules, rows.Err()
	}

	return dominosRules, nil
}

// UpdateByID a "dominoRule" in "public"."domino_rules" by its ""id""
func UpdateByID(db pogo.DB, id int64, dominoRule *Input) (*DominoRule, error) {
	// add values to input, overriding existing keys if present in the input
	dominoRule = dominoRule.ID(id)

	// get the columns
	fields := dominoRule.columns()

	// don't update the keys
	delete(fields, "id")

	// prepare the slices
	_c, _i, _v := slice(fields, 1)

	// setup the update fields
	var _u []string
	for i, c := range _c {
		_u = append(_u, c+" = "+_i[i])
	}

	// return an error if no update input is provided
	if len(_u) == 0 {
		return nil, errors.New("dominorule.UpdateByID: no input provided")
	}

	// sql query
	sqlstr := `UPDATE "public"."domino_rules" SET ` +
		strings.Join(_u, ", ") + ` ` +
		`WHERE "id" = $1 ` +
		`RETURNING "created_at", "id", "name", "owner", "trigger", "updated_at"`

	// setup the query
	values := []interface{}{}
	values = append(values, id)
	values = append(values, _v...)

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, values...)
	}

	// run the query
	var _dominoRule DominoRule
	row := db.QueryRow(context.TODO(), sqlstr, values...)
	if e := row.Scan(&_dominoRule.CreatedAt, &_dominoRule.ID, &_dominoRule.Name, &_dominoRule.Owner, &_dominoRule.Trigger, &_dominoRule.UpdatedAt); e != nil {
		if pogo.IsNoRows(e) {
			return nil, ErrDominoRuleNotFound
		}
		return nil, e
	}

	return &_dominoRule, nil
}

// UpdateByID a "dominoRule" in "public"."domino_rules" by its ""id""
func (*Model) UpdateByID(db pogo.DB, id int64, dominoRule *Input) (*DominoRule, error) {
	// add values to input, overriding existing keys if present in the input
	dominoRule = dominoRule.ID(id)

	// get the columns
	fields := dominoRule.columns()

	// don't update the keys
	delete(fields, "id")

	// prepare the slices
	_c, _i, _v := slice(fields, 1)

	// setup the update fields
	var _u []string
	for i, c := range _c {
		_u = append(_u, c+" = "+_i[i])
	}

	// return an error if no update input is provided
	if len(_u) == 0 {
		return nil, errors.New("dominorule.UpdateByID: no input provided")
	}

	// sql query
	sqlstr := `UPDATE "public"."domino_rules" SET ` +
		strings.Join(_u, ", ") + ` ` +
		`WHERE "id" = $1 ` +
		`RETURNING "created_at", "id", "name", "owner", "trigger", "updated_at"`

	// setup the query
	values := []interface{}{}
	values = append(values, id)
	values = append(values, _v...)

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, values...)
	}

	// run the query
	var _dominoRule DominoRule
	row := db.QueryRow(context.TODO(), sqlstr, values...)
	if e := row.Scan(&_dominoRule.CreatedAt, &_dominoRule.ID, &_dominoRule.Name, &_dominoRule.Owner, &_dominoRule.Trigger, &_dominoRule.UpdatedAt); e != nil {
		if pogo.IsNoRows(e) {
			return nil, ErrDominoRuleNotFound
		}
		return nil, e
	}

	return &_dominoRule, nil
}

// Delete `DominoRule`s by some conditions. Returns the first result.
// Warning: This can delete more than 1 row
func Delete(db pogo.DB, conds ...pogo.Condition) (*DominoRule, error) {
	_s, _v, err := pogo.Conditions(conds...)
	if err != nil {
		return nil, err
	}

	// sql delete query
	sqlstr := `DELETE FROM "public"."domino_rules" ` +
		_s + ` ` +
		`RETURNING "created_at", "id", "name", "owner", "trigger", "updated_at"`

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, _v...)
	}

	var _dominoRule DominoRule
	row := db.QueryRow(context.TODO(), sqlstr, _v...)
	if e := row.Scan(&_dominoRule.CreatedAt, &_dominoRule.ID, &_dominoRule.Name, &_dominoRule.Owner, &_dominoRule.Trigger, &_dominoRule.UpdatedAt); e != nil {
		if pogo.IsNoRows(e) {
			return nil, ErrDominoRuleNotFound
		}
		return nil, e
	}

	return &_dominoRule, nil
}

// Delete `DominoRule`s by some conditions. Returns the first result.
// Warning: This can delete more than 1 row
func (*Model) Delete(db pogo.DB, conds ...pogo.Condition) (*DominoRule, error) {
	_s, _v, err := pogo.Conditions(conds...)
	if err != nil {
		return nil, err
	}

	// sql delete query
	sqlstr := `DELETE FROM "public"."domino_rules" ` +
		_s + ` ` +
		`RETURNING "created_at", "id", "name", "owner", "trigger", "updated_at"`

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, _v...)
	}

	var _dominoRule DominoRule
	row := db.QueryRow(context.TODO(), sqlstr, _v...)
	if e := row.Scan(&_dominoRule.CreatedAt, &_dominoRule.ID, &_dominoRule.Name, &_dominoRule.Owner, &_dominoRule.Trigger, &_dominoRule.UpdatedAt); e != nil {
		if pogo.IsNoRows(e) {
			return nil, ErrDominoRuleNotFound
		}
		return nil, e
	}

	return &_dominoRule, nil
}

// DeleteMany `DominoRule`s by some conditions, returning all results.
func DeleteMany(db pogo.DB, conds ...pogo.Condition) ([]*DominoRule, error) {
	dominosRules := []*DominoRule{}

	_s, _v, err := pogo.Conditions(conds...)
	if err != nil {
		return dominosRules, err
	}

	// sql delete query
	sqlstr := `DELETE FROM "public"."domino_rules" ` +
		_s + ` ` +
		`RETURNING "created_at", "id", "name", "owner", "trigger", "updated_at"`

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, _v...)
	}

	rows, err := db.Query(context.TODO(), sqlstr, _v...)
	if err != nil {
		return dominosRules, err
	}
	defer rows.Close()

	for rows.Next() {
		var _dominoRule DominoRule
		if e := rows.Scan(&_dominoRule.CreatedAt, &_dominoRule.ID, &_dominoRule.Name, &_dominoRule.Owner, &_dominoRule.Trigger, &_dominoRule.UpdatedAt); e != nil {
			if pogo.IsNoRows(e) {
				return dominosRules, ErrDominoRuleNotFound
			}
			return dominosRules, err
		}
		dominosRules = append(dominosRules, &_dominoRule)
	}
	if rows.Err() != nil {
		return dominosRules, rows.Err()
	}

	return dominosRules, nil
}

// DeleteMany `DominoRule`s by some conditions, returning all results.
func (*Model) DeleteMany(db pogo.DB, conds ...pogo.Condition) ([]*DominoRule, error) {
	dominosRules := []*DominoRule{}

	_s, _v, err := pogo.Conditions(conds...)
	if err != nil {
		return dominosRules, err
	}

	// sql delete query
	sqlstr := `DELETE FROM "public"."domino_rules" ` +
		_s + ` ` +
		`RETURNING "created_at", "id", "name", "owner", "trigger", "updated_at"`

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, _v...)
	}

	rows, err := db.Query(context.TODO(), sqlstr, _v...)
	if err != nil {
		return dominosRules, err
	}
	defer rows.Close()

	for rows.Next() {
		var _dominoRule DominoRule
		if e := rows.Scan(&_dominoRule.CreatedAt, &_dominoRule.ID, &_dominoRule.Name, &_dominoRule.Owner, &_dominoRule.Trigger, &_dominoRule.UpdatedAt); e != nil {
			if pogo.IsNoRows(e) {
				return dominosRules, ErrDominoRuleNotFound
			}
			return dominosRules, err
		}
		dominosRules = append(dominosRules, &_dominoRule)
	}
	if rows.Err() != nil {
		return dominosRules, rows.Err()
	}

	return dominosRules, nil
}

// DeleteByID deletes a "dominoRule"
func DeleteByID(db pogo.DB, id int64) (*DominoRule, error) {
	// sql delete query
	sqlstr := `DELETE FROM "public"."domino_rules" ` +
		`WHERE "id" = $1 ` +
		`RETURNING "created_at", "id", "name", "owner", "trigger", "updated_at"`

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, id)
	}

	// run the query
	var _dominoRule DominoRule
	row := db.QueryRow(context.TODO(), sqlstr, id)
	if e := row.Scan(&_dominoRule.CreatedAt, &_dominoRule.ID, &_dominoRule.Name, &_dominoRule.Owner, &_dominoRule.Trigger, &_dominoRule.UpdatedAt); e != nil {
		if pogo.IsNoRows(e) {
			return nil, ErrDominoRuleNotFound
		}
		return nil, e
	}

	return &_dominoRule, nil
}

// DeleteByID deletes a "dominoRule"
func (*Model) DeleteByID(db pogo.DB, id int64) (*DominoRule, error) {
	// sql delete query
	sqlstr := `DELETE FROM "public"."domino_rules" ` +
		`WHERE "id" = $1 ` +
		`RETURNING "created_at", "id", "name", "owner", "trigger", "updated_at"`

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, id)
	}

	// run the query
	var _dominoRule DominoRule
	row := db.QueryRow(context.TODO(), sqlstr, id)
	if e := row.Scan(&_dominoRule.CreatedAt, &_dominoRule.ID, &_dominoRule.Name, &_dominoRule.Owner, &_dominoRule.Trigger, &_dominoRule.UpdatedAt); e != nil {
		if pogo.IsNoRows(e) {
			return nil, ErrDominoRuleNotFound
		}
		return nil, e
	}

	return &_dominoRule, nil
}

// Upsert inserts a `"public"."domino_rules"`, updating the row if `"id"` already exists.
func Upsert(db pogo.DB, dominoRule *Input) (*DominoRule, error) {
	// get all the non-nil columns and prepare them for the query
	_c, _i, _v := slice(dominoRule.columns(), 0)

	// setup the update fields
	var _u []string
	for _, c := range _c {
		_u = append(_u, c+" = excluded."+c)
	}

	// sql query
	sqlstr := `INSERT INTO "public"."domino_rules" (` + strings.Join(_c, ", ") + `) ` +
		`VALUES (` + strings.Join(_i, ", ") + `) ` +
		`ON CONFLICT ("id") ` +
		`DO UPDATE SET ` + strings.Join(_u, ", ") + ` ` +
		`RETURNING "created_at", "id", "name", "owner", "trigger", "updated_at"`

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, _v...)
	}

	// run query
	var _dominoRule DominoRule
	row := db.QueryRow(context.TODO(), sqlstr, _v...)
	if e := row.Scan(&_dominoRule.CreatedAt, &_dominoRule.ID, &_dominoRule.Name, &_dominoRule.Owner, &_dominoRule.Trigger, &_dominoRule.UpdatedAt); e != nil && !pogo.IsNoRows(e) {
		return nil, e
	}

	return &_dominoRule, nil
}

// Upsert inserts a `"public"."domino_rules"`, updating the row if `"id"` already exists.
func (*Model) Upsert(db pogo.DB, dominoRule *Input) (*DominoRule, error) {
	// get all the non-nil columns and prepare them for the query
	_c, _i, _v := slice(dominoRule.columns(), 0)

	// setup the update fields
	var _u []string
	for _, c := range _c {
		_u = append(_u, c+" = excluded."+c)
	}

	// sql query
	sqlstr := `INSERT INTO "public"."domino_rules" (` + strings.Join(_c, ", ") + `) ` +
		`VALUES (` + strings.Join(_i, ", ") + `) ` +
		`ON CONFLICT ("id") ` +
		`DO UPDATE SET ` + strings.Join(_u, ", ") + ` ` +
		`RETURNING "created_at", "id", "name", "owner", "trigger", "updated_at"`

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, _v...)
	}

	// run query
	var _dominoRule DominoRule
	row := db.QueryRow(context.TODO(), sqlstr, _v...)
	if e := row.Scan(&_dominoRule.CreatedAt, &_dominoRule.ID, &_dominoRule.Name, &_dominoRule.Owner, &_dominoRule.Trigger, &_dominoRule.UpdatedAt); e != nil && !pogo.IsNoRows(e) {
		return nil, e
	}

	return &_dominoRule, nil
}

// UpsertByOwnerAndTrigger inserts a `"public"."domino_rules"`, updating the row if `"owner", "trigger"` already exists.
func UpsertByOwnerAndTrigger(db pogo.DB, owner string, trigger string, dominoRule *Input) (*DominoRule, error) {
	// add values to input, overriding existing keys if present in the input
	dominoRule = dominoRule.Owner(owner).Trigger(trigger)

	// get all the non-nil columns and prepare them for the query
	_c, _i, _v := slice(dominoRule.columns(), 0)

	// setup the update fields
	var _u []string
	for _, c := range _c {
		_u = append(_u, c+" = excluded."+c)
	}

	// sql query
	sqlstr := `INSERT INTO "public"."domino_rules" (` + strings.Join(_c, ", ") + `) ` +
		`VALUES (` + strings.Join(_i, ", ") + `) ` +
		`ON CONFLICT ("owner", "trigger") ` +
		`DO UPDATE SET ` + strings.Join(_u, ", ") + ` ` +
		`RETURNING "created_at", "id", "name", "owner", "trigger", "updated_at"`

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, _v...)
	}

	// run query
	var _dominoRule DominoRule
	row := db.QueryRow(context.TODO(), sqlstr, _v...)
	if e := row.Scan(&_dominoRule.CreatedAt, &_dominoRule.ID, &_dominoRule.Name, &_dominoRule.Owner, &_dominoRule.Trigger, &_dominoRule.UpdatedAt); e != nil && !pogo.IsNoRows(e) {
		return nil, e
	}

	return &_dominoRule, nil
}

// UpsertByOwnerAndTrigger inserts a `"public"."domino_rules"`, updating the row if `"owner", "trigger"` already exists.
func (*Model) UpsertByOwnerAndTrigger(db pogo.DB, owner string, trigger string, dominoRule *Input) (*DominoRule, error) {
	// add values to input, overriding existing keys if present in the input
	dominoRule = dominoRule.Owner(owner).Trigger(trigger)

	// get all the non-nil columns and prepare them for the query
	_c, _i, _v := slice(dominoRule.columns(), 0)

	// setup the update fields
	var _u []string
	for _, c := range _c {
		_u = append(_u, c+" = excluded."+c)
	}

	// sql query
	sqlstr := `INSERT INTO "public"."domino_rules" (` + strings.Join(_c, ", ") + `) ` +
		`VALUES (` + strings.Join(_i, ", ") + `) ` +
		`ON CONFLICT ("owner", "trigger") ` +
		`DO UPDATE SET ` + strings.Join(_u, ", ") + ` ` +
		`RETURNING "created_at", "id", "name", "owner", "trigger", "updated_at"`

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, _v...)
	}

	// run query
	var _dominoRule DominoRule
	row := db.QueryRow(context.TODO(), sqlstr, _v...)
	if e := row.Scan(&_dominoRule.CreatedAt, &_dominoRule.ID, &_dominoRule.Name, &_dominoRule.Owner, &_dominoRule.Trigger, &_dominoRule.UpdatedAt); e != nil && !pogo.IsNoRows(e) {
		return nil, e
	}

	return &_dominoRule, nil
}

// UpsertByID inserts a `"public"."domino_rules"`, updating the row if `"id"` already exists.
func UpsertByID(db pogo.DB, id int64, dominoRule *Input) (*DominoRule, error) {
	// add values to input, overriding existing keys if present in the input
	dominoRule = dominoRule.ID(id)

	// get all the non-nil columns and prepare them for the query
	_c, _i, _v := slice(dominoRule.columns(), 0)

	// setup the update fields
	var _u []string
	for _, c := range _c {
		_u = append(_u, c+" = excluded."+c)
	}

	// sql query
	sqlstr := `INSERT INTO "public"."domino_rules" (` + strings.Join(_c, ", ") + `) ` +
		`VALUES (` + strings.Join(_i, ", ") + `) ` +
		`ON CONFLICT ("id") ` +
		`DO UPDATE SET ` + strings.Join(_u, ", ") + ` ` +
		`RETURNING "created_at", "id", "name", "owner", "trigger", "updated_at"`

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, _v...)
	}

	// run query
	var _dominoRule DominoRule
	row := db.QueryRow(context.TODO(), sqlstr, _v...)
	if e := row.Scan(&_dominoRule.CreatedAt, &_dominoRule.ID, &_dominoRule.Name, &_dominoRule.Owner, &_dominoRule.Trigger, &_dominoRule.UpdatedAt); e != nil && !pogo.IsNoRows(e) {
		return nil, e
	}

	return &_dominoRule, nil
}

// UpsertByID inserts a `"public"."domino_rules"`, updating the row if `"id"` already exists.
func (*Model) UpsertByID(db pogo.DB, id int64, dominoRule *Input) (*DominoRule, error) {
	// add values to input, overriding existing keys if present in the input
	dominoRule = dominoRule.ID(id)

	// get all the non-nil columns and prepare them for the query
	_c, _i, _v := slice(dominoRule.columns(), 0)

	// setup the update fields
	var _u []string
	for _, c := range _c {
		_u = append(_u, c+" = excluded."+c)
	}

	// sql query
	sqlstr := `INSERT INTO "public"."domino_rules" (` + strings.Join(_c, ", ") + `) ` +
		`VALUES (` + strings.Join(_i, ", ") + `) ` +
		`ON CONFLICT ("id") ` +
		`DO UPDATE SET ` + strings.Join(_u, ", ") + ` ` +
		`RETURNING "created_at", "id", "name", "owner", "trigger", "updated_at"`

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, _v...)
	}

	// run query
	var _dominoRule DominoRule
	row := db.QueryRow(context.TODO(), sqlstr, _v...)
	if e := row.Scan(&_dominoRule.CreatedAt, &_dominoRule.ID, &_dominoRule.Name, &_dominoRule.Owner, &_dominoRule.Trigger, &_dominoRule.UpdatedAt); e != nil && !pogo.IsNoRows(e) {
		return nil, e
	}

	return &_dominoRule, nil
}

// slice converts our columns into something the sql driver can understand
func slice(columns map[string]interface{}, offset int) (c []string, i []string, v []interface{}) {
	n := offset + 1
	for col, val := range columns {
		c = append(c, strconv.Quote(col))
		i = append(i, "$"+strconv.Itoa(n))
		v = append(v, val)
		n++
	}
	return c, i, v
}
