package dominocondition

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"strconv"
	"strings"

	"github.com/matthewmueller/domino/pgdomino/internal/pogo"
)

// GENERATED BY POGO. DO NOT EDIT.

// ErrDominoConditionNotFound returned if the "public"."domino_conditions" is not found
var ErrDominoConditionNotFound = errors.New("dominoCondition not found")

// DominoCondition result data for "public"."domino_conditions"
type DominoCondition struct {
	Field    string          `json:"field,omitempty"`
	ID       int64           `json:"id,omitempty"`
	Op       string          `json:"op,omitempty"`
	Position int             `json:"position,omitempty"`
	RuleID   int64           `json:"rule_id,omitempty"`
	Value    json.RawMessage `json:"value,omitempty"`
}

var _ pogo.Row = (*DominoCondition)(nil)

// Decode implements pogo.Row
func (dc *DominoCondition) Decode(dominoCondition any) error {
	_dominoCondition, ok := dominoCondition.(*DominoCondition)
	if !ok {
		return fmt.Errorf(`dominoCondition decode: "%T" is not a "*DominoCondition"`, dominoCondition)
	}
	*_dominoCondition = *dc
	return nil
}

// New "public"."domino_conditions" input
func New() *Input {
	return &Input{}
}

// Input data for "public"."domino_conditions"
type Input struct {
	field    *string
	id       *int64
	op       *string
	position *int
	ruleID   *int64
	value    *json.RawMessage
}

var _ pogo.Insertable = (*Input)(nil)

// Field sets the field
func (dc *Input) Field(field string) *Input {
	dc.field = &field
	return dc
}

// ID sets the id
func (dc *Input) ID(id int64) *Input {
	dc.id = &id
	return dc
}

// Op sets the op
func (dc *Input) Op(op string) *Input {
	dc.op = &op
	return dc
}

// Position sets the position
func (dc *Input) Position(position int) *Input {
	dc.position = &position
	return dc
}

// RuleID sets the rule_id
func (dc *Input) RuleID(ruleID int64) *Input {
	dc.ruleID = &ruleID
	return dc
}

// Value sets the value
func (dc *Input) Value(value json.RawMessage) *Input {
	dc.value = &value
	return dc
}

// MarshalJSON marshals the "dominoCondition" into JSON
func (dc *Input) MarshalJSON() ([]byte, error) {
	return json.Marshal(dc)
}

// UnmarshalJSON unmarshals json to a "dominoCondition"
func (dc *Input) UnmarshalJSON(data []byte) error {
	return json.Unmarshal(data, dc)
}

// String of the input
// TODO: make this more useful
func (dc *Input) String() string {
	return `"public"."domino_conditions"`
}

func (dc *Input) columns() map[string]any {
	columns := make(map[string]any)

	if dc.field != nil {
		columns["field"] = *dc.field
	}

	if dc.id != nil {
		columns["id"] = *dc.id
	}

	if dc.op != nil {
		columns["op"] = *dc.op
	}

	if dc.position != nil {
		columns["position"] = *dc.position
	}

	if dc.ruleID != nil {
		columns["rule_id"] = *dc.ruleID
	}

	if dc.value != nil {
		columns["value"] = *dc.value
	}

	return columns
}

// Insert implements pogo.Insertable
func (dc *Input) Insert(db pogo.DB) (pogo.Row, error) {
	return Insert(db, dc)
}

// NewFilter creates a new filter
func NewFilter() *Filter {
	return &Filter{}
}

// Filter filters for "public"."domino_conditions"
type Filter struct {
	formats []string
	values  []any
	error   error
}

var _ pogo.Condition = (*Filter)(nil)

// Clause fn
func (f *Filter) Clause() *pogo.Clause {
	return &pogo.Clause{
		Type:   "WHERE",
		Format: strings.Join(f.formats, " AND "),
		Params: f.values,
		Error:  f.error,
	}
}

// And filter
// func (f *Filter) And(filters ...*Filter) *Filter {
//   var clauses []string
//   for _, filter := range filters {
//     _ = filter
//     // clauses = append(clauses, string(filter.Condition()))
//   }
//   f.clauses = append(f.clauses, strings.Join(clauses, " AND "))
//   return f
// }

// Or filter
// func (f *Filter) Or(filters ...*Filter) *Filter {
//   var clauses []string
//   for _, filter := range filters {
//     _ = filter
//     // clauses = append(clauses, string(filter.Condition()))
//   }
//   f.clauses = append(f.clauses, strings.Join(clauses, " OR "))
//   return f
// }

// Field field equals
func (f *Filter) Field(v string) *Filter {
	f.formats = append(f.formats, `"field" = %s`)
	f.values = append(f.values, v)
	return f
}

// FieldNot field doesn't equal
func (f *Filter) FieldNot(v string) *Filter {
	f.formats = append(f.formats, `"field" != %s`)
	f.values = append(f.values, v)
	return f
}

// FieldContains field contains
func (f *Filter) FieldContains(v string) *Filter {
	f.formats = append(f.formats, `"field" LIKE '%%' || %s || '%%'`)
	f.values = append(f.values, v)
	return f
}

// FieldNotContains field doesn't contain
func (f *Filter) FieldNotContains(v string) *Filter {
	f.formats = append(f.formats, `"field" NOT LIKE '%%' || %s || '%%'`)
	f.values = append(f.values, v)
	return f
}

// FieldStartsWith field starts with
func (f *Filter) FieldStartsWith(v string) *Filter {
	f.formats = append(f.formats, `"field" LIKE %s || '%%'`)
	f.values = append(f.values, v)
	return f
}

// FieldNotStartsWith field doesn't start with
func (f *Filter) FieldNotStartsWith(v string) *Filter {
	f.formats = append(f.formats, `"field" NOT LIKE %s || '%%'`)
	f.values = append(f.values, v)
	return f
}

// FieldEndsWith field ends with
func (f *Filter) FieldEndsWith(v string) *Filter {
	f.formats = append(f.formats, `"field" LIKE '%%' || %s`)
	f.values = append(f.values, v)
	return f
}

// FieldNotEndsWith field doesn't end with
func (f *Filter) FieldNotEndsWith(v string) *Filter {
	f.formats = append(f.formats, `"field" NOT LIKE '%%' || %s`)
	f.values = append(f.values, v)
	return f
}

// FieldLt field is less than
func (f *Filter) FieldLt(v string) *Filter {
	f.formats = append(f.formats, `"field" < %s`)
	f.values = append(f.values, v)
	return f
}

// FieldLte field is less than or equal
func (f *Filter) FieldLte(v string) *Filter {
	f.formats = append(f.formats, `"field" <= %s`)
	f.values = append(f.values, v)
	return f
}

// FieldGt field is greater than
func (f *Filter) FieldGt(v string) *Filter {
	f.formats = append(f.formats, `"field" > %s`)
	f.values = append(f.values, v)
	return f
}

// FieldGte field is greater than or equal
func (f *Filter) FieldGte(v string) *Filter {
	f.formats = append(f.formats, `"field" >= %s`)
	f.values = append(f.values, v)
	return f
}

// FieldIn field is in
func (f *Filter) FieldIn(v ...string) *Filter {
	var rs []string
	if len(v) == 0 {
		f.formats = append(f.formats, `false`)
		return f
	}
	for range v {
		rs = append(rs, "%s")
	}
	f.formats = append(f.formats, fmt.Sprintf(`"field" IN (%s)`, strings.Join(rs, `, `)))
	for _, i := range v {
		f.values = append(f.values, i)
	}
	return f
}

// FieldNotIn field is not in
func (f *Filter) FieldNotIn(v ...string) *Filter {
	var rs []string
	if len(v) == 0 {
		f.formats = append(f.formats, `false`)
		return f
	}
	for range v {
		rs = append(rs, "%s")
	}
	f.formats = append(f.formats, fmt.Sprintf(`"field" NOT IN (%s)`, strings.Join(rs, `, `)))
	for _, i := range v {
		f.values = append(f.values, i)
	}
	return f
}

// ID id equals
func (f *Filter) ID(v int64) *Filter {
	f.formats = append(f.formats, `"id" = %s`)
	f.values = append(f.values, v)
	return f
}

// IDNot id doesn't equal
func (f *Filter) IDNot(v int64) *Filter {
	f.formats = append(f.formats, `"id" != %s`)
	f.values = append(f.values, v)
	return f
}

// IDLt id is less than
func (f *Filter) IDLt(v int64) *Filter {
	f.formats = append(f.formats, `"id" < %s`)
	f.values = append(f.values, v)
	return f
}

// IDLte id is less than or equal
func (f *Filter) IDLte(v int64) *Filter {
	f.formats = append(f.formats, `"id" <= %s`)
	f.values = append(f.values, v)
	return f
}

// IDGt id is greater than
func (f *Filter) IDGt(v int64) *Filter {
	f.formats = append(f.formats, `"id" > %s`)
	f.values = append(f.values, v)
	return f
}

// IDGte id is greater than or equal
func (f *Filter) IDGte(v int64) *Filter {
	f.formats = append(f.formats, `"id" >= %s`)
	f.values = append(f.values, v)
	return f
}

// IDIn id is in
func (f *Filter) IDIn(v ...int64) *Filter {
	var rs []string
	if len(v) == 0 {
		f.formats = append(f.formats, `false`)
		return f
	}
	for range v {
		rs = append(rs, "%s")
	}
	f.formats = append(f.formats, fmt.Sprintf(`"id" IN (%s)`, strings.Join(rs, `, `)))
	for _, i := range v {
		f.values = append(f.values, i)
	}
	return f
}

// IDNotIn id is not in
func (f *Filter) IDNotIn(v ...int64) *Filter {
	var rs []string
	if len(v) == 0 {
		f.formats = append(f.formats, `false`)
		return f
	}
	for range v {
		rs = append(rs, "%s")
	}
	f.formats = append(f.formats, fmt.Sprintf(`"id" NOT IN (%s)`, strings.Join(rs, `, `)))
	for _, i := range v {
		f.values = append(f.values, i)
	}
	return f
}

// Op op equals
func (f *Filter) Op(v string) *Filter {
	f.formats = append(f.formats, `"op" = %s`)
	f.values = append(f.values, v)
	return f
}

// OpNot op doesn't equal
func (f *Filter) OpNot(v string) *Filter {
	f.formats = append(f.formats, `"op" != %s`)
	f.values = append(f.values, v)
	return f
}

// OpContains op contains
func (f *Filter) OpContains(v string) *Filter {
	f.formats = append(f.formats, `"op" LIKE '%%' || %s || '%%'`)
	f.values = append(f.values, v)
	return f
}

// OpNotContains op doesn't contain
func (f *Filter) OpNotContains(v string) *Filter {
	f.formats = append(f.formats, `"op" NOT LIKE '%%' || %s || '%%'`)
	f.values = append(f.values, v)
	return f
}

// OpStartsWith op starts with
func (f *Filter) OpStartsWith(v string) *Filter {
	f.formats = append(f.formats, `"op" LIKE %s || '%%'`)
	f.values = append(f.values, v)
	return f
}

// OpNotStartsWith op doesn't start with
func (f *Filter) OpNotStartsWith(v string) *Filter {
	f.formats = append(f.formats, `"op" NOT LIKE %s || '%%'`)
	f.values = append(f.values, v)
	return f
}

// OpEndsWith op ends with
func (f *Filter) OpEndsWith(v string) *Filter {
	f.formats = append(f.formats, `"op" LIKE '%%' || %s`)
	f.values = append(f.values, v)
	return f
}

// OpNotEndsWith op doesn't end with
func (f *Filter) OpNotEndsWith(v string) *Filter {
	f.formats = append(f.formats, `"op" NOT LIKE '%%' || %s`)
	f.values = append(f.values, v)
	return f
}

// OpLt op is less than
func (f *Filter) OpLt(v string) *Filter {
	f.formats = append(f.formats, `"op" < %s`)
	f.values = append(f.values, v)
	return f
}

// OpLte op is less than or equal
func (f *Filter) OpLte(v string) *Filter {
	f.formats = append(f.formats, `"op" <= %s`)
	f.values = append(f.values, v)
	return f
}

// OpGt op is greater than
func (f *Filter) OpGt(v string) *Filter {
	f.formats = append(f.formats, `"op" > %s`)
	f.values = append(f.values, v)
	return f
}

// OpGte op is greater than or equal
func (f *Filter) OpGte(v string) *Filter {
	f.formats = append(f.formats, `"op" >= %s`)
	f.values = append(f.values, v)
	return f
}

// OpIn op is in
func (f *Filter) OpIn(v ...string) *Filter {
	var rs []string
	if len(v) == 0 {
		f.formats = append(f.formats, `false`)
		return f
	}
	for range v {
		rs = append(rs, "%s")
	}
	f.formats = append(f.formats, fmt.Sprintf(`"op" IN (%s)`, strings.Join(rs, `, `)))
	for _, i := range v {
		f.values = append(f.values, i)
	}
	return f
}

// OpNotIn op is not in
func (f *Filter) OpNotIn(v ...string) *Filter {
	var rs []string
	if len(v) == 0 {
		f.formats = append(f.formats, `false`)
		return f
	}
	for range v {
		rs = append(rs, "%s")
	}
	f.formats = append(f.formats, fmt.Sprintf(`"op" NOT IN (%s)`, strings.Join(rs, `, `)))
	for _, i := range v {
		f.values = append(f.values, i)
	}
	return f
}

// Position position equals
func (f *Filter) Position(v int) *Filter {
	f.formats = append(f.formats, `"position" = %s`)
	f.values = append(f.values, v)
	return f
}

// PositionNot position doesn't equal
func (f *Filter) PositionNot(v int) *Filter {
	f.formats = append(f.formats, `"position" != %s`)
	f.values = append(f.values, v)
	return f
}

// PositionLt position is less than
func (f *Filter) PositionLt(v int) *Filter {
	f.formats = append(f.formats, `"position" < %s`)
	f.values = append(f.values, v)
	return f
}

// PositionLte position is less than or equal
func (f *Filter) PositionLte(v int) *Filter {
	f.formats = append(f.formats, `"position" <= %s`)
	f.values = append(f.values, v)
	return f
}

// PositionGt position is greater than
func (f *Filter) PositionGt(v int) *Filter {
	f.formats = append(f.formats, `"position" > %s`)
	f.values = append(f.values, v)
	return f
}

// PositionGte position is greater than or equal
func (f *Filter) PositionGte(v int) *Filter {
	f.formats = append(f.formats, `"position" >= %s`)
	f.values = append(f.values, v)
	return f
}

// PositionIn position is in
func (f *Filter) PositionIn(v ...int) *Filter {
	var rs []string
	if len(v) == 0 {
		f.formats = append(f.formats, `false`)
		return f
	}
	for range v {
		rs = append(rs, "%s")
	}
	f.formats = append(f.formats, fmt.Sprintf(`"position" IN (%s)`, strings.Join(rs, `, `)))
	for _, i := range v {
		f.values = append(f.values, i)
	}
	return f
}

// PositionNotIn position is not in
func (f *Filter) PositionNotIn(v ...int) *Filter {
	var rs []string
	if len(v) == 0 {
		f.formats = append(f.formats, `false`)
		return f
	}
	for range v {
		rs = append(rs, "%s")
	}
	f.formats = append(f.formats, fmt.Sprintf(`"position" NOT IN (%s)`, strings.Join(rs, `, `)))
	for _, i := range v {
		f.values = append(f.values, i)
	}
	return f
}

// RuleID rule_id equals
func (f *Filter) RuleID(v int64) *Filter {
	f.formats = append(f.formats, `"rule_id" = %s`)
	f.values = append(f.values, v)
	return f
}

// RuleIDNot rule_id doesn't equal
func (f *Filter) RuleIDNot(v int64) *Filter {
	f.formats = append(f.formats, `"rule_id" != %s`)
	f.values = append(f.values, v)
	return f
}

// RuleIDLt rule_id is less than
func (f *Filter) RuleIDLt(v int64) *Filter {
	f.formats = append(f.formats, `"rule_id" < %s`)
	f.values = append(f.values, v)
	return f
}

// RuleIDLte rule_id is less than or equal
func (f *Filter) RuleIDLte(v int64) *Filter {
	f.formats = append(f.formats, `"rule_id" <= %s`)
	f.values = append(f.values, v)
	return f
}

// RuleIDGt rule_id is greater than
func (f *Filter) RuleIDGt(v int64) *Filter {
	f.formats = append(f.formats, `"rule_id" > %s`)
	f.values = append(f.values, v)
	return f
}

// RuleIDGte rule_id is greater than or equal
func (f *Filter) RuleIDGte(v int64) *Filter {
	f.formats = append(f.formats, `"rule_id" >= %s`)
	f.values = append(f.values, v)
	return f
}

// RuleIDIn rule_id is in
func (f *Filter) RuleIDIn(v ...int64) *Filter {
	var rs []string
	if len(v) == 0 {
		f.formats = append(f.formats, `false`)
		return f
	}
	for range v {
		rs = append(rs, "%s")
	}
	f.formats = append(f.formats, fmt.Sprintf(`"rule_id" IN (%s)`, strings.Join(rs, `, `)))
	for _, i := range v {
		f.values = append(f.values, i)
	}
	return f
}

// RuleIDNotIn rule_id is not in
func (f *Filter) RuleIDNotIn(v ...int64) *Filter {
	var rs []string
	if len(v) == 0 {
		f.formats = append(f.formats, `false`)
		return f
	}
	for range v {
		rs = append(rs, "%s")
	}
	f.formats = append(f.formats, fmt.Sprintf(`"rule_id" NOT IN (%s)`, strings.Join(rs, `, `)))
	for _, i := range v {
		f.values = append(f.values, i)
	}
	return f
}

// OrderBy specificies the ORDERBy BY <order>
type OrderBy string

const (
	// ASC sorts by ascending order
	ASC OrderBy = "ASC"

	// DESC sorts by descending order
	DESC OrderBy = "DESC"
)

// NewOrder fn
func NewOrder() *Orderer {
	return &Orderer{}
}

var _ pogo.Condition = (*Orderer)(nil)

// Orderer orders the given fields
type Orderer struct {
	formats []string
}

// Clause fn
func (o *Orderer) Clause() *pogo.Clause {
	return &pogo.Clause{
		Type:   "ORDER BY",
		Format: strings.Join(o.formats, ", "),
	}
}

// Field sorts "field" by an expression
func (o *Orderer) Field(order OrderBy) *Orderer {
	o.formats = append(o.formats, fmt.Sprintf(`"field" %s`, order))
	return o
}

// ID sorts "id" by an expression
func (o *Orderer) ID(order OrderBy) *Orderer {
	o.formats = append(o.formats, fmt.Sprintf(`"id" %s`, order))
	return o
}

// Op sorts "op" by an expression
func (o *Orderer) Op(order OrderBy) *Orderer {
	o.formats = append(o.formats, fmt.Sprintf(`"op" %s`, order))
	return o
}

// Position sorts "position" by an expression
func (o *Orderer) Position(order OrderBy) *Orderer {
	o.formats = append(o.formats, fmt.Sprintf(`"position" %s`, order))
	return o
}

// RuleID sorts "rule_id" by an expression
func (o *Orderer) RuleID(order OrderBy) *Orderer {
	o.formats = append(o.formats, fmt.Sprintf(`"rule_id" %s`, order))
	return o
}

// Value sorts "value" by an expression
func (o *Orderer) Value(order OrderBy) *Orderer {
	o.formats = append(o.formats, fmt.Sprintf(`"value" %s`, order))
	return o
}

// Model is an empty struct that has all the methods.
// It's primarly used for embedding the methods
// into higher-level models.
type Model struct{}

// Insert a ""public"."domino_conditions"" into the "public"."domino_conditions"
func Insert(db pogo.DB, dominoCondition *Input) (*DominoCondition, error) {
	// get all the non-nil columns and prepare them for the query
	_c, _i, _v := slice(dominoCondition.columns(), 0)
	_ = _i

	// sql insert query, primary key provided by sequence
	var sqlstr string
	if len(_c) == 0 {
		sqlstr = `
      INSERT INTO "public"."domino_conditions"
      DEFAULT VALUES
      RETURNING "field", "id", "op", "position", "rule_id", "value"
    `
	} else {
		sqlstr = `
      INSERT INTO "public"."domino_conditions" (` + strings.Join(_c, ", ") + `)
      VALUES (` + strings.Join(_i, ", ") + `)
      RETURNING "field", "id", "op", "position", "rule_id", "value"
    `
	}

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, _v...)
	}

	var _dominoCondition DominoCondition
	row := db.QueryRow(context.TODO(), sqlstr, _v...)
	if e := row.Scan(&_dominoCondition.Field, &_dominoCondition.ID, &_dominoCondition.Op, &_dominoCondition.Position, &_dominoCondition.RuleID, &_dominoCondition.Value); e != nil {
		return nil, e
	}

	return &_dominoCondition, nil
}

// Insert a ""public"."domino_conditions"" into the "public"."domino_conditions"
func (*Model) Insert(db pogo.DB, dominoCondition *Input) (*DominoCondition, error) {
	// get all the non-nil columns and prepare them for the query
	_c, _i, _v := slice(dominoCondition.columns(), 0)
	_ = _i

	// sql insert query, primary key provided by sequence
	var sqlstr string
	if len(_c) == 0 {
		sqlstr = `
      INSERT INTO "public"."domino_conditions"
      DEFAULT VALUES
      RETURNING "field", "id", "op", "position", "rule_id", "value"
    `
	} else {
		sqlstr = `
      INSERT INTO "public"."domino_conditions" (` + strings.Join(_c, ", ") + `)
      VALUES (` + strings.Join(_i, ", ") + `)
      RETURNING "field", "id", "op", "position", "rule_id", "value"
    `
	}

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, _v...)
	}

	var _dominoCondition DominoCondition
	row := db.QueryRow(context.TODO(), sqlstr, _v...)
	if e := row.Scan(&_dominoCondition.Field, &_dominoCondition.ID, &_dominoCondition.Op, &_dominoCondition.Position, &_dominoCondition.RuleID, &_dominoCondition.Value); e != nil {
		return nil, e
	}

	return &_dominoCondition, nil
}

// InsertMany ""public"."domino_conditions"" into the "public"."domino_conditions"
func InsertMany(db pogo.DB, dominosConditions ...*Input) ([]*DominoCondition, error) {
	_dominosConditions := []*DominoCondition{}
	for _, dominoCondition := range dominosConditions {
		_dominoCondition, err := Insert(db, dominoCondition)
		if err != nil {
			return _dominosConditions, err
		}
		_dominosConditions = append(_dominosConditions, _dominoCondition)
	}
	return _dominosConditions, nil
}

// InsertMany ""public"."domino_conditions"" into the "public"."domino_conditions"
func (*Model) InsertMany(db pogo.DB, dominosConditions ...*Input) ([]*DominoCondition, error) {
	_dominosConditions := []*DominoCondition{}
	for _, dominoCondition := range dominosConditions {
		_dominoCondition, err := Insert(db, dominoCondition)
		if err != nil {
			return _dominosConditions, err
		}
		_dominosConditions = append(_dominosConditions, _dominoCondition)
	}
	return _dominosConditions, nil
}

// Find a `DominoCondition` by some conditions.
func Find(db pogo.DB, conds ...pogo.Condition) (*DominoCondition, error) {
	_s, _v, err := pogo.Conditions(conds...)
	if err != nil {
		return nil, err
	}

	// sql select query, primary key provided by sequence
	sqlstr := `SELECT "field", "id", "op", "position", "rule_id", "value" ` +
		`FROM "public"."domino_conditions" ` +
		_s

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, _v...)
	}

	var _dominoCondition DominoCondition
	row := db.QueryRow(context.TODO(), sqlstr, _v...)
	if e := row.Scan(&_dominoCondition.Field, &_dominoCondition.ID, &_dominoCondition.Op, &_dominoCondition.Position, &_dominoCondition.RuleID, &_dominoCondition.Value); e != nil {
		if pogo.IsNoRows(e) {
			return nil, ErrDominoConditionNotFound
		}
		return nil, e
	}

	return &_dominoCondition, nil
}

// Find a `DominoCondition` by some conditions.
func (*Model) Find(db pogo.DB, conds ...pogo.Condition) (*DominoCondition, error) {
	_s, _v, err := pogo.Conditions(conds...)
	if err != nil {
		return nil, err
	}

	// sql select query, primary key provided by sequence
	sqlstr := `SELECT "field", "id", "op", "position", "rule_id", "value" ` +
		`FROM "public"."domino_conditions" ` +
		_s

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, _v...)
	}

	var _dominoCondition DominoCondition
	row := db.QueryRow(context.TODO(), sqlstr, _v...)
	if e := row.Scan(&_dominoCondition.Field, &_dominoCondition.ID, &_dominoCondition.Op, &_dominoCondition.Position, &_dominoCondition.RuleID, &_dominoCondition.Value); e != nil {
		if pogo.IsNoRows(e) {
			return nil, ErrDominoConditionNotFound
		}
		return nil, e
	}

	return &_dominoCondition, nil
}

// FindByID a `DominoCondition` by some conditions.
func FindByID(db pogo.DB, id int64) (*DominoCondition, error) {
	// sql select query, primary key provided by sequence
	sqlstr := `
    SELECT "field", "id", "op", "position", "rule_id", "value"
    FROM "public"."domino_conditions"
    WHERE "id" = $1
  `

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, id)
	}

	var _dominoCondition DominoCondition
	row := db.QueryRow(context.TODO(), sqlstr, id)
	if e := row.Scan(&_dominoCondition.Field, &_dominoCondition.ID, &_dominoCondition.Op, &_dominoCondition.Position, &_dominoCondition.RuleID, &_dominoCondition.Value); e != nil {
		if pogo.IsNoRows(e) {
			return nil, ErrDominoConditionNotFound
		}
		return nil, e
	}

	return &_dominoCondition, nil
}

// FindByID a `DominoCondition` by some conditions.
func (*Model) FindByID(db pogo.DB, id int64) (*DominoCondition, error) {
	// sql select query, primary key provided by sequence
	sqlstr := `
    SELECT "field", "id", "op", "position", "rule_id", "value"
    FROM "public"."domino_conditions"
    WHERE "id" = $1
  `

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, id)
	}

	var _dominoCondition DominoCondition
	row := db.QueryRow(context.TODO(), sqlstr, id)
	if e := row.Scan(&_dominoCondition.Field, &_dominoCondition.ID, &_dominoCondition.Op, &_dominoCondition.Position, &_dominoCondition.RuleID, &_dominoCondition.Value); e != nil {
		if pogo.IsNoRows(e) {
			return nil, ErrDominoConditionNotFound
		}
		return nil, e
	}

	return &_dominoCondition, nil
}

// FindByPositionAndRuleID find a dominoCondition by position and rule_id
func FindByPositionAndRuleID(db pogo.DB, position int, ruleID int64) (*DominoCondition, error) {
	// sql select query, primary key provided by sequence
	sqlstr := `
    SELECT "field", "id", "op", "position", "rule_id", "value"
    FROM "public"."domino_conditions"
    WHERE "position" = $1 AND "rule_id" = $2
  `

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, position, ruleID)
	}

	var _dominoCondition DominoCondition
	row := db.QueryRow(context.TODO(), sqlstr, position, ruleID)
	err := row.Scan(&_dominoCondition.Field, &_dominoCondition.ID, &_dominoCondition.Op, &_dominoCondition.Position, &_dominoCondition.RuleID, &_dominoCondition.Value)
	if err != nil {
		if pogo.IsNoRows(err) {
			return nil, ErrDominoConditionNotFound
		}
		return nil, err
	}

	return &_dominoCondition, nil
}

// FindByPositionAndRuleID find a dominoCondition by position and rule_id
func (*Model) FindByPositionAndRuleID(db pogo.DB, position int, ruleID int64) (*DominoCondition, error) {
	// sql select query, primary key provided by sequence
	sqlstr := `
    SELECT "field", "id", "op", "position", "rule_id", "value"
    FROM "public"."domino_conditions"
    WHERE "position" = $1 AND "rule_id" = $2
  `

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, position, ruleID)
	}

	var _dominoCondition DominoCondition
	row := db.QueryRow(context.TODO(), sqlstr, position, ruleID)
	err := row.Scan(&_dominoCondition.Field, &_dominoCondition.ID, &_dominoCondition.Op, &_dominoCondition.Position, &_dominoCondition.RuleID, &_dominoCondition.Value)
	if err != nil {
		if pogo.IsNoRows(err) {
			return nil, ErrDominoConditionNotFound
		}
		return nil, err
	}
	return &_dominoCondition, nil
}

// FindMany finds many "public"."domino_conditions" by a condition
func FindMany(db pogo.DB, conds ...pogo.Condition) ([]*DominoCondition, error) {
	dominosConditions := []*DominoCondition{}

	_s, _v, err := pogo.Conditions(conds...)
	if err != nil {
		return dominosConditions, err
	}

	// sql select query, primary key provided by sequence
	sqlstr := `SELECT "field", "id", "op", "position", "rule_id", "value" ` +
		`FROM "public"."domino_conditions" ` +
		_s

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, _v...)
	}

	rows, err := db.Query(context.TODO(), sqlstr, _v...)
	if err != nil {
		return dominosConditions, err
	}
	defer rows.Close()

	for rows.Next() {
		var _dominoCondition DominoCondition
		if e := rows.Scan(&_dominoCondition.Field, &_dominoCondition.ID, &_dominoCondition.Op, &_dominoCondition.Position, &_dominoCondition.RuleID, &_dominoCondition.Value); e != nil {
			if pogo.IsNoRows(e) {
				return dominosConditions, ErrDominoConditionNotFound
			}
			return dominosConditions, err
		}
		dominosConditions = append(dominosConditions, &_dominoCondition)
	}
	if rows.Err() != nil {
		return dominosConditions, rows.Err()
	}

	return dominosConditions, nil
}

// FindMany finds many "public"."domino_conditions" by a condition
func (*Model) FindMany(db pogo.DB, conds ...pogo.Condition) ([]*DominoCondition, error) {
	dominosConditions := []*DominoCondition{}

	_s, _v, err := pogo.Conditions(conds...)
	if err != nil {
		return dominosConditions, err
	}

	// sql select query, primary key provided by sequence
	sqlstr := `SELECT "field", "id", "op", "position", "rule_id", "value" ` +
		`FROM "public"."domino_conditions" ` +
		_s

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, _v...)
	}

	rows, err := db.Query(context.TODO(), sqlstr, _v...)
	if err != nil {
		return dominosConditions, err
	}
	defer rows.Close()

	for rows.Next() {
		var _dominoCondition DominoCondition
		if e := rows.Scan(&_dominoCondition.Field, &_dominoCondition.ID, &_dominoCondition.Op, &_dominoCondition.Position, &_dominoCondition.RuleID, &_dominoCondition.Value); e != nil {
			if pogo.IsNoRows(e) {
				return dominosConditions, ErrDominoConditionNotFound
			}
			return dominosConditions, err
		}
		dominosConditions = append(dominosConditions, &_dominoCondition)
	}
	if rows.Err() != nil {
		return dominosConditions, rows.Err()
	}

	return dominosConditions, nil
}

// Update ""public"."domino_conditions"" rows in "public"."domino_conditions" by a condition, returning 1 result
func Update(db pogo.DB, dominoCondition *Input, conds ...pogo.Condition) (*DominoCondition, error) {
	_s, _v, err := pogo.Conditions(conds...)
	if err != nil {
		return nil, err
	}

	fields := dominoCondition.columns()

	// prepare the slices
	_c, _i, _v2 := slice(fields, len(_v))
	_v = append(_v, _v2...)

	// setup the update fields
	var _u []string
	for i, c := range _c {
		_u = append(_u, c+" = "+_i[i])
	}

	// return an error if no update input is provided
	if len(_u) == 0 {
		return nil, errors.New("dominocondition.Update: no input provided")
	}

	// sql query
	sqlstr := `UPDATE "public"."domino_conditions" SET ` +
		strings.Join(_u, ", ") + ` ` +
		_s + ` ` +
		`RETURNING "field", "id", "op", "position", "rule_id", "value"`

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, _v...)
	}

	// run the query
	var _dominoCondition DominoCondition
	row := db.QueryRow(context.TODO(), sqlstr, _v...)
	if e := row.Scan(&_dominoCondition.Field, &_dominoCondition.ID, &_dominoCondition.Op, &_dominoCondition.Position, &_dominoCondition.RuleID, &_dominoCondition.Value); e != nil {
		if pogo.IsNoRows(e) {
			return nil, ErrDominoConditionNotFound
		}
		return nil, e
	}

	return &_dominoCondition, nil
}

// Update ""public"."domino_conditions"" rows in "public"."domino_conditions" by a condition, returning 1 result
func (*Model) Update(db pogo.DB, dominoCondition *Input, conds ...pogo.Condition) (*DominoCondition, error) {
	_s, _v, err := pogo.Conditions(conds...)
	if err != nil {
		return nil, err
	}

	fields := dominoCondition.columns()

	// prepare the slices
	_c, _i, _v2 := slice(fields, len(_v))
	_v = append(_v, _v2...)

	// setup the update fields
	var _u []string
	for i, c := range _c {
		_u = append(_u, c+" = "+_i[i])
	}

	// return an error if no update input is provided
	if len(_u) == 0 {
		return nil, errors.New("dominocondition.Update: no input provided")
	}

	// sql query
	sqlstr := `UPDATE "public"."domino_conditions" SET ` +
		strings.Join(_u, ", ") + ` ` +
		_s + ` ` +
		`RETURNING "field", "id", "op", "position", "rule_id", "value"`

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, _v...)
	}

	// run the query
	var _dominoCondition DominoCondition
	row := db.QueryRow(context.TODO(), sqlstr, _v...)
	if e := row.Scan(&_dominoCondition.Field, &_dominoCondition.ID, &_dominoCondition.Op, &_dominoCondition.Position, &_dominoCondition.RuleID, &_dominoCondition.Value); e != nil {
		if pogo.IsNoRows(e) {
			return nil, ErrDominoConditionNotFound
		}
		return nil, e
	}

	return &_dominoCondition, nil
}

// UpdateMany updates ""public"."domino_conditions"" rows in "public"."domino_conditions" by conditions, returning all results
func UpdateMany(db pogo.DB, dominoCondition *Input, conds ...pogo.Condition) ([]*DominoCondition, error) {
	dominosConditions := []*DominoCondition{}

	_s, _v, err := pogo.Conditions(conds...)
	if err != nil {
		return nil, err
	}

	fields := dominoCondition.columns()

	// prepare the slices
	_c, _i, _v2 := slice(fields, len(_v))
	_v = append(_v, _v2...)

	// setup the update fields
	var _u []string
	for i, c := range _c {
		_u = append(_u, c+" = "+_i[i])
	}

	// return an error if no update input is provided
	if len(_u) == 0 {
		return nil, errors.New("dominocondition.UpdateMany: no input provided")
	}

	// sql query
	sqlstr := `UPDATE "public"."domino_conditions" SET ` +
		strings.Join(_u, ", ") + ` ` +
		_s + ` ` +
		`RETURNING "field", "id", "op", "position", "rule_id", "value"`

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, _v...)
	}

	rows, err := db.Query(context.TODO(), sqlstr, _v...)
	if err != nil {
		return dominosConditions, err
	}
	defer rows.Close()

	for rows.Next() {
		var _dominoCondition DominoCondition
		if e := rows.Scan(&_dominoCondition.Field, &_dominoCondition.ID, &_dominoCondition.Op, &_dominoCondition.Position, &_dominoCondition.RuleID, &_dominoCondition.Value); e != nil {
			if pogo.IsNoRows(e) {
				return dominosConditions, ErrDominoConditionNotFound
			}
			return dominosConditions, err
		}
		dominosConditions = append(dominosConditions, &_dominoCondition)
	}
	if rows.Err() != nil {
		return dominosConditions, rows.Err()
	}

	return dominosConditions, nil
}

// UpdateMany updates ""public"."domino_conditions"" rows in "public"."domino_conditions" by conditions, returning all results
func (*Model) UpdateMany(db pogo.DB, dominoCondition *Input, conds ...pogo.Condition) ([]*DominoCondition, error) {
	dominosConditions := []*DominoCondition{}

	_s, _v, err := pogo.Conditions(conds...)
	if err != nil {
		return nil, err
	}

	fields := dominoCondition.columns()

	// prepare the slices
	_c, _i, _v2 := slice(fields, len(_v))
	_v = append(_v, _v2...)

	// setup the update fields
	var _u []string
	for i, c := range _c {
		_u = append(_u, c+" = "+_i[i])
	}

	// return an error if no update input is provided
	if len(_u) == 0 {
		return nil, errors.New("dominocondition.UpdateMany: no input provided")
	}

	// sql query
	sqlstr := `UPDATE "public"."domino_conditions" SET ` +
		strings.Join(_u, ", ") + ` ` +
		_s + ` ` +
		`RETURNING "field", "id", "op", "position", "rule_id", "value"`

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, _v...)
	}

	rows, err := db.Query(context.TODO(), sqlstr, _v...)
	if err != nil {
		return dominosConditions, err
	}
	defer rows.Close()

	for rows.Next() {
		var _dominoCondition DominoCondition
		if e := rows.Scan(&_dominoCondition.Field, &_dominoCondition.ID, &_dominoCondition.Op, &_dominoCondition.Position, &_dominoCondition.RuleID, &_dominoCondition.Value); e != nil {
			if pogo.IsNoRows(e) {
				return dominosConditions, ErrDominoConditionNotFound
			}
			return dominosConditions, err
		}
		dominosConditions = append(dominosConditions, &_dominoCondition)
	}
	if rows.Err() != nil {
		return dominosConditions, rows.Err()
	}

	return dominosConditions, nil
}

// UpdateByID a "dominoCondition" in "public"."domino_conditions" by its ""id""
func UpdateByID(db pogo.DB, id int64, dominoCondition *Input) (*DominoCondition, error) {
	// add values to input, overriding existing keys if present in the input
	dominoCondition = dominoCondition.ID(id)

	// get the columns
	fields := dominoCondition.columns()

	// don't update the keys
	delete(fields, "id")

	// prepare the slices
	_c, _i, _v := slice(fields, 1)

	// setup the update fields
	var _u []string
	for i, c := range _c {
		_u = append(_u, c+" = "+_i[i])
	}

	// return an error if no update input is provided
	if len(_u) == 0 {
		return nil, errors.New("dominocondition.UpdateByID: no input provided")
	}

	// sql query
	sqlstr := `UPDATE "public"."domino_conditions" SET ` +
		strings.Join(_u, ", ") + ` ` +
		`WHERE "id" = $1 ` +
		`RETURNING "field", "id", "op", "position", "rule_id", "value"`

	// setup the query
	values := []any{}
	values = append(values, id)
	values = append(values, _v...)

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, values...)
	}

	// run the query
	var _dominoCondition DominoCondition
	row := db.QueryRow(context.TODO(), sqlstr, values...)
	if e := row.Scan(&_dominoCondition.Field, &_dominoCondition.ID, &_dominoCondition.Op, &_dominoCondition.Position, &_dominoCondition.RuleID, &_dominoCondition.Value); e != nil {
		if pogo.IsNoRows(e) {
			return nil, ErrDominoConditionNotFound
		}
		return nil, e
	}

	return &_dominoCondition, nil
}

// UpdateByID a "dominoCondition" in "public"."domino_conditions" by its ""id""
func (*Model) UpdateByID(db pogo.DB, id int64, dominoCondition *Input) (*DominoCondition, error) {
	// add values to input, overriding existing keys if present in the input
	dominoCondition = dominoCondition.ID(id)

	// get the columns
	fields := dominoCondition.columns()

	// don't update the keys
	delete(fields, "id")

	// prepare the slices
	_c, _i, _v := slice(fields, 1)

	// setup the update fields
	var _u []string
	for i, c := range _c {
		_u = append(_u, c+" = "+_i[i])
	}

	// return an error if no update input is provided
	if len(_u) == 0 {
		return nil, errors.New("dominocondition.UpdateByID: no input provided")
	}

	// sql query
	sqlstr := `UPDATE "public"."domino_conditions" SET ` +
		strings.Join(_u, ", ") + ` ` +
		`WHERE "id" = $1 ` +
		`RETURNING "field", "id", "op", "position", "rule_id", "value"`

	// setup the query
	values := []any{}
	values = append(values, id)
	values = append(values, _v...)

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, values...)
	}

	// run the query
	var _dominoCondition DominoCondition
	row := db.QueryRow(context.TODO(), sqlstr, values...)
	if e := row.Scan(&_dominoCondition.Field, &_dominoCondition.ID, &_dominoCondition.Op, &_dominoCondition.Position, &_dominoCondition.RuleID, &_dominoCondition.Value); e != nil {
		if pogo.IsNoRows(e) {
			return nil, ErrDominoConditionNotFound
		}
		return nil, e
	}

	return &_dominoCondition, nil
}

// UpdateByPositionAndRuleID find a DominoCondition
func UpdateByPositionAndRuleID(db pogo.DB, position int, ruleID int64, dominoCondition *Input) (*DominoCondition, error) {
	// add values to input, overriding existing keys if present in the input
	dominoCondition = dominoCondition.Position(position).RuleID(ruleID)

	// get the columns
	fields := dominoCondition.columns()

	// don't update the keys
	delete(fields, "position")
	delete(fields, "rule_id")

	// prepare the slices
	_c, _i, _v := slice(fields, 2)

	// setup the update fields
	var _u []string
	for i, c := range _c {
		_u = append(_u, c+" = "+_i[i])
	}

	// return an error if no update input is provided
	if len(_u) == 0 {
		return nil, errors.New("dominocondition.UpdateByPositionAndRuleID: no input provided")
	}

	// sql query
	sqlstr := `UPDATE "public"."domino_conditions" SET ` +
		strings.Join(_u, ", ") + ` ` +
		`WHERE "position" = $1 AND "rule_id" = $2 ` +
		`RETURNING "field", "id", "op", "position", "rule_id", "value"`

	// setup the query
	values := []any{}
	values = append(values, position)
	values = append(values, ruleID)
	values = append(values, _v...)

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, values...)
	}

	// run the query
	var _dominoCondition DominoCondition
	row := db.QueryRow(context.TODO(), sqlstr, values...)
	if e := row.Scan(&_dominoCondition.Field, &_dominoCondition.ID, &_dominoCondition.Op, &_dominoCondition.Position, &_dominoCondition.RuleID, &_dominoCondition.Value); e != nil {
		if pogo.IsNoRows(e) {
			return nil, ErrDominoConditionNotFound
		}
		return nil, e
	}

	return &_dominoCondition, nil
}

// UpdateByPositionAndRuleID find a DominoCondition
func (*Model) UpdateByPositionAndRuleID(db pogo.DB, position int, ruleID int64, dominoCondition *Input) (*DominoCondition, error) {
	// add values to input, overriding existing keys if present in the input
	dominoCondition = dominoCondition.Position(position).RuleID(ruleID)

	// get the columns
	fields := dominoCondition.columns()

	// don't update the keys
	delete(fields, "position")
	delete(fields, "rule_id")

	// prepare the slices
	_c, _i, _v := slice(fields, 2)

	// setup the update fields
	var _u []string
	for i, c := range _c {
		_u = append(_u, c+" = "+_i[i])
	}

	// return an error if no update input is provided
	if len(_u) == 0 {
		return nil, errors.New("dominocondition.UpdateByPositionAndRuleID: no input provided")
	}

	// sql query
	sqlstr := `UPDATE "public"."domino_conditions" SET ` +
		strings.Join(_u, ", ") + ` ` +
		`WHERE "position" = $1 AND "rule_id" = $2 ` +
		`RETURNING "field", "id", "op", "position", "rule_id", "value"`

	// setup the query
	values := []any{}
	values = append(values, position)
	values = append(values, ruleID)
	values = append(values, _v...)

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, values...)
	}

	// run the query
	var _dominoCondition DominoCondition
	row := db.QueryRow(context.TODO(), sqlstr, values...)
	if e := row.Scan(&_dominoCondition.Field, &_dominoCondition.ID, &_dominoCondition.Op, &_dominoCondition.Position, &_dominoCondition.RuleID, &_dominoCondition.Value); e != nil {
		if pogo.IsNoRows(e) {
			return nil, ErrDominoConditionNotFound
		}
		return nil, e
	}

	return &_dominoCondition, nil
}

// Delete `DominoCondition`s by some conditions. Returns the first result.
// Warning: This can delete more than 1 row
func Delete(db pogo.DB, conds ...pogo.Condition) (*DominoCondition, error) {
	_s, _v, err := pogo.Conditions(conds...)
	if err != nil {
		return nil, err
	}

	// sql delete query
	sqlstr := `DELETE FROM "public"."domino_conditions" ` +
		_s + ` ` +
		`RETURNING "field", "id", "op", "position", "rule_id", "value"`

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, _v...)
	}

	var _dominoCondition DominoCondition
	row := db.QueryRow(context.TODO(), sqlstr, _v...)
	if e := row.Scan(&_dominoCondition.Field, &_dominoCondition.ID, &_dominoCondition.Op, &_dominoCondition.Position, &_dominoCondition.RuleID, &_dominoCondition.Value); e != nil {
		if pogo.IsNoRows(e) {
			return nil, ErrDominoConditionNotFound
		}
		return nil, e
	}

	return &_dominoCondition, nil
}

// Delete `DominoCondition`s by some conditions. Returns the first result.
// Warning: This can delete more than 1 row
func (*Model) Delete(db pogo.DB, conds ...pogo.Condition) (*DominoCondition, error) {
	_s, _v, err := pogo.Conditions(conds...)
	if err != nil {
		return nil, err
	}

	// sql delete query
	sqlstr := `DELETE FROM "public"."domino_conditions" ` +
		_s + ` ` +
		`RETURNING "field", "id", "op", "position", "rule_id", "value"`

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, _v...)
	}

	var _dominoCondition DominoCondition
	row := db.QueryRow(context.TODO(), sqlstr, _v...)
	if e := row.Scan(&_dominoCondition.Field, &_dominoCondition.ID, &_dominoCondition.Op, &_dominoCondition.Position, &_dominoCondition.RuleID, &_dominoCondition.Value); e != nil {
		if pogo.IsNoRows(e) {
			return nil, ErrDominoConditionNotFound
		}
		return nil, e
	}

	return &_dominoCondition, nil
}

// DeleteMany `DominoCondition`s by some conditions, returning all results.
func DeleteMany(db pogo.DB, conds ...pogo.Condition) ([]*DominoCondition, error) {
	dominosConditions := []*DominoCondition{}

	_s, _v, err := pogo.Conditions(conds...)
	if err != nil {
		return dominosConditions, err
	}

	// sql delete query
	sqlstr := `DELETE FROM "public"."domino_conditions" ` +
		_s + ` ` +
		`RETURNING "field", "id", "op", "position", "rule_id", "value"`

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, _v...)
	}

	rows, err := db.Query(context.TODO(), sqlstr, _v...)
	if err != nil {
		return dominosConditions, err
	}
	defer rows.Close()

	for rows.Next() {
		var _dominoCondition DominoCondition
		if e := rows.Scan(&_dominoCondition.Field, &_dominoCondition.ID, &_dominoCondition.Op, &_dominoCondition.Position, &_dominoCondition.RuleID, &_dominoCondition.Value); e != nil {
			if pogo.IsNoRows(e) {
				return dominosConditions, ErrDominoConditionNotFound
			}
			return dominosConditions, err
		}
		dominosConditions = append(dominosConditions, &_dominoCondition)
	}
	if rows.Err() != nil {
		return dominosConditions, rows.Err()
	}

	return dominosConditions, nil
}

// DeleteMany `DominoCondition`s by some conditions, returning all results.
func (*Model) DeleteMany(db pogo.DB, conds ...pogo.Condition) ([]*DominoCondition, error) {
	dominosConditions := []*DominoCondition{}

	_s, _v, err := pogo.Conditions(conds...)
	if err != nil {
		return dominosConditions, err
	}

	// sql delete query
	sqlstr := `DELETE FROM "public"."domino_conditions" ` +
		_s + ` ` +
		`RETURNING "field", "id", "op", "position", "rule_id", "value"`

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, _v...)
	}

	rows, err := db.Query(context.TODO(), sqlstr, _v...)
	if err != nil {
		return dominosConditions, err
	}
	defer rows.Close()

	for rows.Next() {
		var _dominoCondition DominoCondition
		if e := rows.Scan(&_dominoCondition.Field, &_dominoCondition.ID, &_dominoCondition.Op, &_dominoCondition.Position, &_dominoCondition.RuleID, &_dominoCondition.Value); e != nil {
			if pogo.IsNoRows(e) {
				return dominosConditions, ErrDominoConditionNotFound
			}
			return dominosConditions, err
		}
		dominosConditions = append(dominosConditions, &_dominoCondition)
	}
	if rows.Err() != nil {
		return dominosConditions, rows.Err()
	}

	return dominosConditions, nil
}

// DeleteByID deletes a "dominoCondition"
func DeleteByID(db pogo.DB, id int64) (*DominoCondition, error) {
	// sql delete query
	sqlstr := `DELETE FROM "public"."domino_conditions" ` +
		`WHERE "id" = $1 ` +
		`RETURNING "field", "id", "op", "position", "rule_id", "value"`

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, id)
	}

	// run the query
	var _dominoCondition DominoCondition
	row := db.QueryRow(context.TODO(), sqlstr, id)
	if e := row.Scan(&_dominoCondition.Field, &_dominoCondition.ID, &_dominoCondition.Op, &_dominoCondition.Position, &_dominoCondition.RuleID, &_dominoCondition.Value); e != nil {
		if pogo.IsNoRows(e) {
			return nil, ErrDominoConditionNotFound
		}
		return nil, e
	}

	return &_dominoCondition, nil
}

// DeleteByID deletes a "dominoCondition"
func (*Model) DeleteByID(db pogo.DB, id int64) (*DominoCondition, error) {
	// sql delete query
	sqlstr := `DELETE FROM "public"."domino_conditions" ` +
		`WHERE "id" = $1 ` +
		`RETURNING "field", "id", "op", "position", "rule_id", "value"`

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, id)
	}

	// run the query
	var _dominoCondition DominoCondition
	row := db.QueryRow(context.TODO(), sqlstr, id)
	if e := row.Scan(&_dominoCondition.Field, &_dominoCondition.ID, &_dominoCondition.Op, &_dominoCondition.Position, &_dominoCondition.RuleID, &_dominoCondition.Value); e != nil {
		if pogo.IsNoRows(e) {
			return nil, ErrDominoConditionNotFound
		}
		return nil, e
	}

	return &_dominoCondition, nil
}

// DeleteByPositionAndRuleID deletes a "dominoCondition"
func DeleteByPositionAndRuleID(db pogo.DB, position int, ruleID int64) (*DominoCondition, error) {
	// sql delete query
	sqlstr := `DELETE FROM "public"."domino_conditions" ` +
		`WHERE "position" = $1 AND "rule_id" = $2 ` +
		`RETURNING "field", "id", "op", "position", "rule_id", "value"`

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, position, ruleID)
	}

	// run the query
	var _dominoCondition DominoCondition
	row := db.QueryRow(context.TODO(), sqlstr, position, ruleID)
	if e := row.Scan(&_dominoCondition.Field, &_dominoCondition.ID, &_dominoCondition.Op, &_dominoCondition.Position, &_dominoCondition.RuleID, &_dominoCondition.Value); e != nil {
		if pogo.IsNoRows(e) {
			return nil, ErrDominoConditionNotFound
		}
		return nil, e
	}

	return &_dominoCondition, nil
}

// DeleteByPositionAndRuleID deletes a "dominoCondition"
func (*Model) DeleteByPositionAndRuleID(db pogo.DB, position int, ruleID int64) (*DominoCondition, error) {
	// sql delete query
	sqlstr := `DELETE FROM "public"."domino_conditions" ` +
		`WHERE "position" = $1 AND "rule_id" = $2 ` +
		`RETURNING "field", "id", "op", "position", "rule_id", "value"`

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, position, ruleID)
	}

	// run the query
	var _dominoCondition DominoCondition
	row := db.QueryRow(context.TODO(), sqlstr, position, ruleID)
	if e := row.Scan(&_dominoCondition.Field, &_dominoCondition.ID, &_dominoCondition.Op, &_dominoCondition.Position, &_dominoCondition.RuleID, &_dominoCondition.Value); e != nil {
		if pogo.IsNoRows(e) {
			return nil, ErrDominoConditionNotFound
		}
		return nil, e
	}

	return &_dominoCondition, nil
}

// Upsert inserts a `"public"."domino_conditions"`, updating the row if `"id"` already exists.
func Upsert(db pogo.DB, dominoCondition *Input) (*DominoCondition, error) {
	// get all the non-nil columns and prepare them for the query
	_c, _i, _v := slice(dominoCondition.columns(), 0)

	// setup the update fields
	var _u []string
	for _, c := range _c {
		_u = append(_u, c+" = excluded."+c)
	}

	// sql query
	sqlstr := `INSERT INTO "public"."domino_conditions" (` + strings.Join(_c, ", ") + `) ` +
		`VALUES (` + strings.Join(_i, ", ") + `) ` +
		`ON CONFLICT ("id") ` +
		`DO UPDATE SET ` + strings.Join(_u, ", ") + ` ` +
		`RETURNING "field", "id", "op", "position", "rule_id", "value"`

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, _v...)
	}

	// run query
	var _dominoCondition DominoCondition
	row := db.QueryRow(context.TODO(), sqlstr, _v...)
	if e := row.Scan(&_dominoCondition.Field, &_dominoCondition.ID, &_dominoCondition.Op, &_dominoCondition.Position, &_dominoCondition.RuleID, &_dominoCondition.Value); e != nil && !pogo.IsNoRows(e) {
		return nil, e
	}

	return &_dominoCondition, nil
}

// Upsert inserts a `"public"."domino_conditions"`, updating the row if `"id"` already exists.
func (*Model) Upsert(db pogo.DB, dominoCondition *Input) (*DominoCondition, error) {
	// get all the non-nil columns and prepare them for the query
	_c, _i, _v := slice(dominoCondition.columns(), 0)

	// setup the update fields
	var _u []string
	for _, c := range _c {
		_u = append(_u, c+" = excluded."+c)
	}

	// sql query
	sqlstr := `INSERT INTO "public"."domino_conditions" (` + strings.Join(_c, ", ") + `) ` +
		`VALUES (` + strings.Join(_i, ", ") + `) ` +
		`ON CONFLICT ("id") ` +
		`DO UPDATE SET ` + strings.Join(_u, ", ") + ` ` +
		`RETURNING "field", "id", "op", "position", "rule_id", "value"`

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, _v...)
	}

	// run query
	var _dominoCondition DominoCondition
	row := db.QueryRow(context.TODO(), sqlstr, _v...)
	if e := row.Scan(&_dominoCondition.Field, &_dominoCondition.ID, &_dominoCondition.Op, &_dominoCondition.Position, &_dominoCondition.RuleID, &_dominoCondition.Value); e != nil && !pogo.IsNoRows(e) {
		return nil, e
	}

	return &_dominoCondition, nil
}

// UpsertByID inserts a `"public"."domino_conditions"`, updating the row if `"id"` already exists.
func UpsertByID(db pogo.DB, id int64, dominoCondition *Input) (*DominoCondition, error) {
	// add values to input, overriding existing keys if present in the input
	dominoCondition = dominoCondition.ID(id)

	// get all the non-nil columns and prepare them for the query
	_c, _i, _v := slice(dominoCondition.columns(), 0)

	// setup the update fields
	var _u []string
	for _, c := range _c {
		_u = append(_u, c+" = excluded."+c)
	}

	// sql query
	sqlstr := `INSERT INTO "public"."domino_conditions" (` + strings.Join(_c, ", ") + `) ` +
		`VALUES (` + strings.Join(_i, ", ") + `) ` +
		`ON CONFLICT ("id") ` +
		`DO UPDATE SET ` + strings.Join(_u, ", ") + ` ` +
		`RETURNING "field", "id", "op", "position", "rule_id", "value"`

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, _v...)
	}

	// run query
	var _dominoCondition DominoCondition
	row := db.QueryRow(context.TODO(), sqlstr, _v...)
	if e := row.Scan(&_dominoCondition.Field, &_dominoCondition.ID, &_dominoCondition.Op, &_dominoCondition.Position, &_dominoCondition.RuleID, &_dominoCondition.Value); e != nil && !pogo.IsNoRows(e) {
		return nil, e
	}

	return &_dominoCondition, nil
}

// UpsertByID inserts a `"public"."domino_conditions"`, updating the row if `"id"` already exists.
func (*Model) UpsertByID(db pogo.DB, id int64, dominoCondition *Input) (*DominoCondition, error) {
	// add values to input, overriding existing keys if present in the input
	dominoCondition = dominoCondition.ID(id)

	// get all the non-nil columns and prepare them for the query
	_c, _i, _v := slice(dominoCondition.columns(), 0)

	// setup the update fields
	var _u []string
	for _, c := range _c {
		_u = append(_u, c+" = excluded."+c)
	}

	// sql query
	sqlstr := `INSERT INTO "public"."domino_conditions" (` + strings.Join(_c, ", ") + `) ` +
		`VALUES (` + strings.Join(_i, ", ") + `) ` +
		`ON CONFLICT ("id") ` +
		`DO UPDATE SET ` + strings.Join(_u, ", ") + ` ` +
		`RETURNING "field", "id", "op", "position", "rule_id", "value"`

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, _v...)
	}

	// run query
	var _dominoCondition DominoCondition
	row := db.QueryRow(context.TODO(), sqlstr, _v...)
	if e := row.Scan(&_dominoCondition.Field, &_dominoCondition.ID, &_dominoCondition.Op, &_dominoCondition.Position, &_dominoCondition.RuleID, &_dominoCondition.Value); e != nil && !pogo.IsNoRows(e) {
		return nil, e
	}

	return &_dominoCondition, nil
}

// UpsertByPositionAndRuleID inserts a `"public"."domino_conditions"`, updating the row if `"position", "rule_id"` already exists.
func UpsertByPositionAndRuleID(db pogo.DB, position int, ruleID int64, dominoCondition *Input) (*DominoCondition, error) {
	// add values to input, overriding existing keys if present in the input
	dominoCondition = dominoCondition.Position(position).RuleID(ruleID)

	// get all the non-nil columns and prepare them for the query
	_c, _i, _v := slice(dominoCondition.columns(), 0)

	// setup the update fields
	var _u []string
	for _, c := range _c {
		_u = append(_u, c+" = excluded."+c)
	}

	// sql query
	sqlstr := `INSERT INTO "public"."domino_conditions" (` + strings.Join(_c, ", ") + `) ` +
		`VALUES (` + strings.Join(_i, ", ") + `) ` +
		`ON CONFLICT ("position", "rule_id") ` +
		`DO UPDATE SET ` + strings.Join(_u, ", ") + ` ` +
		`RETURNING "field", "id", "op", "position", "rule_id", "value"`

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, _v...)
	}

	// run query
	var _dominoCondition DominoCondition
	row := db.QueryRow(context.TODO(), sqlstr, _v...)
	if e := row.Scan(&_dominoCondition.Field, &_dominoCondition.ID, &_dominoCondition.Op, &_dominoCondition.Position, &_dominoCondition.RuleID, &_dominoCondition.Value); e != nil && !pogo.IsNoRows(e) {
		return nil, e
	}

	return &_dominoCondition, nil
}

// UpsertByPositionAndRuleID inserts a `"public"."domino_conditions"`, updating the row if `"position", "rule_id"` already exists.
func (*Model) UpsertByPositionAndRuleID(db pogo.DB, position int, ruleID int64, dominoCondition *Input) (*DominoCondition, error) {
	// add values to input, overriding existing keys if present in the input
	dominoCondition = dominoCondition.Position(position).RuleID(ruleID)

	// get all the non-nil columns and prepare them for the query
	_c, _i, _v := slice(dominoCondition.columns(), 0)

	// setup the update fields
	var _u []string
	for _, c := range _c {
		_u = append(_u, c+" = excluded."+c)
	}

	// sql query
	sqlstr := `INSERT INTO "public"."domino_conditions" (` + strings.Join(_c, ", ") + `) ` +
		`VALUES (` + strings.Join(_i, ", ") + `) ` +
		`ON CONFLICT ("position", "rule_id") ` +
		`DO UPDATE SET ` + strings.Join(_u, ", ") + ` ` +
		`RETURNING "field", "id", "op", "position", "rule_id", "value"`

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, _v...)
	}

	// run query
	var _dominoCondition DominoCondition
	row := db.QueryRow(context.TODO(), sqlstr, _v...)
	if e := row.Scan(&_dominoCondition.Field, &_dominoCondition.ID, &_dominoCondition.Op, &_dominoCondition.Position, &_dominoCondition.RuleID, &_dominoCondition.Value); e != nil && !pogo.IsNoRows(e) {
		return nil, e
	}

	return &_dominoCondition, nil
}

// slice converts our columns into something the sql driver can understand
func slice(columns map[string]any, offset int) (c []string, i []string, v []any) {
	n := offset + 1
	for col, val := range columns {
		c = append(c, strconv.Quote(col))
		i = append(i, "$"+strconv.Itoa(n))
		v = append(v, val)
		n++
	}
	return c, i, v
}
