package dominoaction

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"strconv"
	"strings"

	"github.com/matthewmueller/domino/pgdomino/internal/pogo"
)

// GENERATED BY POGO. DO NOT EDIT.

// ErrDominoActionNotFound returned if the "public"."domino_actions" is not found
var ErrDominoActionNotFound = errors.New("dominoAction not found")

// DominoAction result data for "public"."domino_actions"
type DominoAction struct {
	ID       int64           `json:"id,omitempty"`
	Name     string          `json:"name,omitempty"`
	Position int             `json:"position,omitempty"`
	RuleID   int64           `json:"rule_id,omitempty"`
	Settings json.RawMessage `json:"settings,omitempty"`
}

var _ pogo.Row = (*DominoAction)(nil)

// Decode implements pogo.Row
func (da *DominoAction) Decode(dominoAction any) error {
	_dominoAction, ok := dominoAction.(*DominoAction)
	if !ok {
		return fmt.Errorf(`dominoAction decode: "%T" is not a "*DominoAction"`, dominoAction)
	}
	*_dominoAction = *da
	return nil
}

// New "public"."domino_actions" input
func New() *Input {
	return &Input{}
}

// Input data for "public"."domino_actions"
type Input struct {
	id       *int64
	name     *string
	position *int
	ruleID   *int64
	settings *json.RawMessage
}

var _ pogo.Insertable = (*Input)(nil)

// ID sets the id
func (da *Input) ID(id int64) *Input {
	da.id = &id
	return da
}

// Name sets the name
func (da *Input) Name(name string) *Input {
	da.name = &name
	return da
}

// Position sets the position
func (da *Input) Position(position int) *Input {
	da.position = &position
	return da
}

// RuleID sets the rule_id
func (da *Input) RuleID(ruleID int64) *Input {
	da.ruleID = &ruleID
	return da
}

// Settings sets the settings
func (da *Input) Settings(settings json.RawMessage) *Input {
	da.settings = &settings
	return da
}

// MarshalJSON marshals the "dominoAction" into JSON
func (da *Input) MarshalJSON() ([]byte, error) {
	return json.Marshal(da)
}

// UnmarshalJSON unmarshals json to a "dominoAction"
func (da *Input) UnmarshalJSON(data []byte) error {
	return json.Unmarshal(data, da)
}

// String of the input
// TODO: make this more useful
func (da *Input) String() string {
	return `"public"."domino_actions"`
}

func (da *Input) columns() map[string]any {
	columns := make(map[string]any)

	if da.id != nil {
		columns["id"] = *da.id
	}

	if da.name != nil {
		columns["name"] = *da.name
	}

	if da.position != nil {
		columns["position"] = *da.position
	}

	if da.ruleID != nil {
		columns["rule_id"] = *da.ruleID
	}

	if da.settings != nil {
		columns["settings"] = *da.settings
	}

	return columns
}

// Insert implements pogo.Insertable
func (da *Input) Insert(db pogo.DB) (pogo.Row, error) {
	return Insert(db, da)
}

// NewFilter creates a new filter
func NewFilter() *Filter {
	return &Filter{}
}

// Filter filters for "public"."domino_actions"
type Filter struct {
	formats []string
	values  []any
	error   error
}

var _ pogo.Condition = (*Filter)(nil)

// Clause fn
func (f *Filter) Clause() *pogo.Clause {
	return &pogo.Clause{
		Type:   "WHERE",
		Format: strings.Join(f.formats, " AND "),
		Params: f.values,
		Error:  f.error,
	}
}

// And filter
// func (f *Filter) And(filters ...*Filter) *Filter {
//   var clauses []string
//   for _, filter := range filters {
//     _ = filter
//     // clauses = append(clauses, string(filter.Condition()))
//   }
//   f.clauses = append(f.clauses, strings.Join(clauses, " AND "))
//   return f
// }

// Or filter
// func (f *Filter) Or(filters ...*Filter) *Filter {
//   var clauses []string
//   for _, filter := range filters {
//     _ = filter
//     // clauses = append(clauses, string(filter.Condition()))
//   }
//   f.clauses = append(f.clauses, strings.Join(clauses, " OR "))
//   return f
// }

// ID id equals
func (f *Filter) ID(v int64) *Filter {
	f.formats = append(f.formats, `"id" = %s`)
	f.values = append(f.values, v)
	return f
}

// IDNot id doesn't equal
func (f *Filter) IDNot(v int64) *Filter {
	f.formats = append(f.formats, `"id" != %s`)
	f.values = append(f.values, v)
	return f
}

// IDLt id is less than
func (f *Filter) IDLt(v int64) *Filter {
	f.formats = append(f.formats, `"id" < %s`)
	f.values = append(f.values, v)
	return f
}

// IDLte id is less than or equal
func (f *Filter) IDLte(v int64) *Filter {
	f.formats = append(f.formats, `"id" <= %s`)
	f.values = append(f.values, v)
	return f
}

// IDGt id is greater than
func (f *Filter) IDGt(v int64) *Filter {
	f.formats = append(f.formats, `"id" > %s`)
	f.values = append(f.values, v)
	return f
}

// IDGte id is greater than or equal
func (f *Filter) IDGte(v int64) *Filter {
	f.formats = append(f.formats, `"id" >= %s`)
	f.values = append(f.values, v)
	return f
}

// IDIn id is in
func (f *Filter) IDIn(v ...int64) *Filter {
	var rs []string
	if len(v) == 0 {
		f.formats = append(f.formats, `false`)
		return f
	}
	for range v {
		rs = append(rs, "%s")
	}
	f.formats = append(f.formats, fmt.Sprintf(`"id" IN (%s)`, strings.Join(rs, `, `)))
	for _, i := range v {
		f.values = append(f.values, i)
	}
	return f
}

// IDNotIn id is not in
func (f *Filter) IDNotIn(v ...int64) *Filter {
	var rs []string
	if len(v) == 0 {
		f.formats = append(f.formats, `false`)
		return f
	}
	for range v {
		rs = append(rs, "%s")
	}
	f.formats = append(f.formats, fmt.Sprintf(`"id" NOT IN (%s)`, strings.Join(rs, `, `)))
	for _, i := range v {
		f.values = append(f.values, i)
	}
	return f
}

// Name name equals
func (f *Filter) Name(v string) *Filter {
	f.formats = append(f.formats, `"name" = %s`)
	f.values = append(f.values, v)
	return f
}

// NameNot name doesn't equal
func (f *Filter) NameNot(v string) *Filter {
	f.formats = append(f.formats, `"name" != %s`)
	f.values = append(f.values, v)
	return f
}

// NameContains name contains
func (f *Filter) NameContains(v string) *Filter {
	f.formats = append(f.formats, `"name" LIKE '%%' || %s || '%%'`)
	f.values = append(f.values, v)
	return f
}

// NameNotContains name doesn't contain
func (f *Filter) NameNotContains(v string) *Filter {
	f.formats = append(f.formats, `"name" NOT LIKE '%%' || %s || '%%'`)
	f.values = append(f.values, v)
	return f
}

// NameStartsWith name starts with
func (f *Filter) NameStartsWith(v string) *Filter {
	f.formats = append(f.formats, `"name" LIKE %s || '%%'`)
	f.values = append(f.values, v)
	return f
}

// NameNotStartsWith name doesn't start with
func (f *Filter) NameNotStartsWith(v string) *Filter {
	f.formats = append(f.formats, `"name" NOT LIKE %s || '%%'`)
	f.values = append(f.values, v)
	return f
}

// NameEndsWith name ends with
func (f *Filter) NameEndsWith(v string) *Filter {
	f.formats = append(f.formats, `"name" LIKE '%%' || %s`)
	f.values = append(f.values, v)
	return f
}

// NameNotEndsWith name doesn't end with
func (f *Filter) NameNotEndsWith(v string) *Filter {
	f.formats = append(f.formats, `"name" NOT LIKE '%%' || %s`)
	f.values = append(f.values, v)
	return f
}

// NameLt name is less than
func (f *Filter) NameLt(v string) *Filter {
	f.formats = append(f.formats, `"name" < %s`)
	f.values = append(f.values, v)
	return f
}

// NameLte name is less than or equal
func (f *Filter) NameLte(v string) *Filter {
	f.formats = append(f.formats, `"name" <= %s`)
	f.values = append(f.values, v)
	return f
}

// NameGt name is greater than
func (f *Filter) NameGt(v string) *Filter {
	f.formats = append(f.formats, `"name" > %s`)
	f.values = append(f.values, v)
	return f
}

// NameGte name is greater than or equal
func (f *Filter) NameGte(v string) *Filter {
	f.formats = append(f.formats, `"name" >= %s`)
	f.values = append(f.values, v)
	return f
}

// NameIn name is in
func (f *Filter) NameIn(v ...string) *Filter {
	var rs []string
	if len(v) == 0 {
		f.formats = append(f.formats, `false`)
		return f
	}
	for range v {
		rs = append(rs, "%s")
	}
	f.formats = append(f.formats, fmt.Sprintf(`"name" IN (%s)`, strings.Join(rs, `, `)))
	for _, i := range v {
		f.values = append(f.values, i)
	}
	return f
}

// NameNotIn name is not in
func (f *Filter) NameNotIn(v ...string) *Filter {
	var rs []string
	if len(v) == 0 {
		f.formats = append(f.formats, `false`)
		return f
	}
	for range v {
		rs = append(rs, "%s")
	}
	f.formats = append(f.formats, fmt.Sprintf(`"name" NOT IN (%s)`, strings.Join(rs, `, `)))
	for _, i := range v {
		f.values = append(f.values, i)
	}
	return f
}

// Position position equals
func (f *Filter) Position(v int) *Filter {
	f.formats = append(f.formats, `"position" = %s`)
	f.values = append(f.values, v)
	return f
}

// PositionNot position doesn't equal
func (f *Filter) PositionNot(v int) *Filter {
	f.formats = append(f.formats, `"position" != %s`)
	f.values = append(f.values, v)
	return f
}

// PositionLt position is less than
func (f *Filter) PositionLt(v int) *Filter {
	f.formats = append(f.formats, `"position" < %s`)
	f.values = append(f.values, v)
	return f
}

// PositionLte position is less than or equal
func (f *Filter) PositionLte(v int) *Filter {
	f.formats = append(f.formats, `"position" <= %s`)
	f.values = append(f.values, v)
	return f
}

// PositionGt position is greater than
func (f *Filter) PositionGt(v int) *Filter {
	f.formats = append(f.formats, `"position" > %s`)
	f.values = append(f.values, v)
	return f
}

// PositionGte position is greater than or equal
func (f *Filter) PositionGte(v int) *Filter {
	f.formats = append(f.formats, `"position" >= %s`)
	f.values = append(f.values, v)
	return f
}

// PositionIn position is in
func (f *Filter) PositionIn(v ...int) *Filter {
	var rs []string
	if len(v) == 0 {
		f.formats = append(f.formats, `false`)
		return f
	}
	for range v {
		rs = append(rs, "%s")
	}
	f.formats = append(f.formats, fmt.Sprintf(`"position" IN (%s)`, strings.Join(rs, `, `)))
	for _, i := range v {
		f.values = append(f.values, i)
	}
	return f
}

// PositionNotIn position is not in
func (f *Filter) PositionNotIn(v ...int) *Filter {
	var rs []string
	if len(v) == 0 {
		f.formats = append(f.formats, `false`)
		return f
	}
	for range v {
		rs = append(rs, "%s")
	}
	f.formats = append(f.formats, fmt.Sprintf(`"position" NOT IN (%s)`, strings.Join(rs, `, `)))
	for _, i := range v {
		f.values = append(f.values, i)
	}
	return f
}

// RuleID rule_id equals
func (f *Filter) RuleID(v int64) *Filter {
	f.formats = append(f.formats, `"rule_id" = %s`)
	f.values = append(f.values, v)
	return f
}

// RuleIDNot rule_id doesn't equal
func (f *Filter) RuleIDNot(v int64) *Filter {
	f.formats = append(f.formats, `"rule_id" != %s`)
	f.values = append(f.values, v)
	return f
}

// RuleIDLt rule_id is less than
func (f *Filter) RuleIDLt(v int64) *Filter {
	f.formats = append(f.formats, `"rule_id" < %s`)
	f.values = append(f.values, v)
	return f
}

// RuleIDLte rule_id is less than or equal
func (f *Filter) RuleIDLte(v int64) *Filter {
	f.formats = append(f.formats, `"rule_id" <= %s`)
	f.values = append(f.values, v)
	return f
}

// RuleIDGt rule_id is greater than
func (f *Filter) RuleIDGt(v int64) *Filter {
	f.formats = append(f.formats, `"rule_id" > %s`)
	f.values = append(f.values, v)
	return f
}

// RuleIDGte rule_id is greater than or equal
func (f *Filter) RuleIDGte(v int64) *Filter {
	f.formats = append(f.formats, `"rule_id" >= %s`)
	f.values = append(f.values, v)
	return f
}

// RuleIDIn rule_id is in
func (f *Filter) RuleIDIn(v ...int64) *Filter {
	var rs []string
	if len(v) == 0 {
		f.formats = append(f.formats, `false`)
		return f
	}
	for range v {
		rs = append(rs, "%s")
	}
	f.formats = append(f.formats, fmt.Sprintf(`"rule_id" IN (%s)`, strings.Join(rs, `, `)))
	for _, i := range v {
		f.values = append(f.values, i)
	}
	return f
}

// RuleIDNotIn rule_id is not in
func (f *Filter) RuleIDNotIn(v ...int64) *Filter {
	var rs []string
	if len(v) == 0 {
		f.formats = append(f.formats, `false`)
		return f
	}
	for range v {
		rs = append(rs, "%s")
	}
	f.formats = append(f.formats, fmt.Sprintf(`"rule_id" NOT IN (%s)`, strings.Join(rs, `, `)))
	for _, i := range v {
		f.values = append(f.values, i)
	}
	return f
}

// OrderBy specificies the ORDERBy BY <order>
type OrderBy string

const (
	// ASC sorts by ascending order
	ASC OrderBy = "ASC"

	// DESC sorts by descending order
	DESC OrderBy = "DESC"
)

// NewOrder fn
func NewOrder() *Orderer {
	return &Orderer{}
}

var _ pogo.Condition = (*Orderer)(nil)

// Orderer orders the given fields
type Orderer struct {
	formats []string
}

// Clause fn
func (o *Orderer) Clause() *pogo.Clause {
	return &pogo.Clause{
		Type:   "ORDER BY",
		Format: strings.Join(o.formats, ", "),
	}
}

// ID sorts "id" by an expression
func (o *Orderer) ID(order OrderBy) *Orderer {
	o.formats = append(o.formats, fmt.Sprintf(`"id" %s`, order))
	return o
}

// Name sorts "name" by an expression
func (o *Orderer) Name(order OrderBy) *Orderer {
	o.formats = append(o.formats, fmt.Sprintf(`"name" %s`, order))
	return o
}

// Position sorts "position" by an expression
func (o *Orderer) Position(order OrderBy) *Orderer {
	o.formats = append(o.formats, fmt.Sprintf(`"position" %s`, order))
	return o
}

// RuleID sorts "rule_id" by an expression
func (o *Orderer) RuleID(order OrderBy) *Orderer {
	o.formats = append(o.formats, fmt.Sprintf(`"rule_id" %s`, order))
	return o
}

// Settings sorts "settings" by an expression
func (o *Orderer) Settings(order OrderBy) *Orderer {
	o.formats = append(o.formats, fmt.Sprintf(`"settings" %s`, order))
	return o
}

// Model is an empty struct that has all the methods.
// It's primarly used for embedding the methods
// into higher-level models.
type Model struct{}

// Insert a ""public"."domino_actions"" into the "public"."domino_actions"
func Insert(db pogo.DB, dominoAction *Input) (*DominoAction, error) {
	// get all the non-nil columns and prepare them for the query
	_c, _i, _v := slice(dominoAction.columns(), 0)
	_ = _i

	// sql insert query, primary key provided by sequence
	var sqlstr string
	if len(_c) == 0 {
		sqlstr = `
      INSERT INTO "public"."domino_actions"
      DEFAULT VALUES
      RETURNING "id", "name", "position", "rule_id", "settings"
    `
	} else {
		sqlstr = `
      INSERT INTO "public"."domino_actions" (` + strings.Join(_c, ", ") + `)
      VALUES (` + strings.Join(_i, ", ") + `)
      RETURNING "id", "name", "position", "rule_id", "settings"
    `
	}

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, _v...)
	}

	var _dominoAction DominoAction
	row := db.QueryRow(context.TODO(), sqlstr, _v...)
	if e := row.Scan(&_dominoAction.ID, &_dominoAction.Name, &_dominoAction.Position, &_dominoAction.RuleID, &_dominoAction.Settings); e != nil {
		return nil, e
	}

	return &_dominoAction, nil
}

// Insert a ""public"."domino_actions"" into the "public"."domino_actions"
func (*Model) Insert(db pogo.DB, dominoAction *Input) (*DominoAction, error) {
	// get all the non-nil columns and prepare them for the query
	_c, _i, _v := slice(dominoAction.columns(), 0)
	_ = _i

	// sql insert query, primary key provided by sequence
	var sqlstr string
	if len(_c) == 0 {
		sqlstr = `
      INSERT INTO "public"."domino_actions"
      DEFAULT VALUES
      RETURNING "id", "name", "position", "rule_id", "settings"
    `
	} else {
		sqlstr = `
      INSERT INTO "public"."domino_actions" (` + strings.Join(_c, ", ") + `)
      VALUES (` + strings.Join(_i, ", ") + `)
      RETURNING "id", "name", "position", "rule_id", "settings"
    `
	}

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, _v...)
	}

	var _dominoAction DominoAction
	row := db.QueryRow(context.TODO(), sqlstr, _v...)
	if e := row.Scan(&_dominoAction.ID, &_dominoAction.Name, &_dominoAction.Position, &_dominoAction.RuleID, &_dominoAction.Settings); e != nil {
		return nil, e
	}

	return &_dominoAction, nil
}

// InsertMany ""public"."domino_actions"" into the "public"."domino_actions"
func InsertMany(db pogo.DB, dominosActions ...*Input) ([]*DominoAction, error) {
	_dominosActions := []*DominoAction{}
	for _, dominoAction := range dominosActions {
		_dominoAction, err := Insert(db, dominoAction)
		if err != nil {
			return _dominosActions, err
		}
		_dominosActions = append(_dominosActions, _dominoAction)
	}
	return _dominosActions, nil
}

// InsertMany ""public"."domino_actions"" into the "public"."domino_actions"
func (*Model) InsertMany(db pogo.DB, dominosActions ...*Input) ([]*DominoAction, error) {
	_dominosActions := []*DominoAction{}
	for _, dominoAction := range dominosActions {
		_dominoAction, err := Insert(db, dominoAction)
		if err != nil {
			return _dominosActions, err
		}
		_dominosActions = append(_dominosActions, _dominoAction)
	}
	return _dominosActions, nil
}

// Find a `DominoAction` by some conditions.
func Find(db pogo.DB, conds ...pogo.Condition) (*DominoAction, error) {
	_s, _v, err := pogo.Conditions(conds...)
	if err != nil {
		return nil, err
	}

	// sql select query, primary key provided by sequence
	sqlstr := `SELECT "id", "name", "position", "rule_id", "settings" ` +
		`FROM "public"."domino_actions" ` +
		_s

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, _v...)
	}

	var _dominoAction DominoAction
	row := db.QueryRow(context.TODO(), sqlstr, _v...)
	if e := row.Scan(&_dominoAction.ID, &_dominoAction.Name, &_dominoAction.Position, &_dominoAction.RuleID, &_dominoAction.Settings); e != nil {
		if pogo.IsNoRows(e) {
			return nil, ErrDominoActionNotFound
		}
		return nil, e
	}

	return &_dominoAction, nil
}

// Find a `DominoAction` by some conditions.
func (*Model) Find(db pogo.DB, conds ...pogo.Condition) (*DominoAction, error) {
	_s, _v, err := pogo.Conditions(conds...)
	if err != nil {
		return nil, err
	}

	// sql select query, primary key provided by sequence
	sqlstr := `SELECT "id", "name", "position", "rule_id", "settings" ` +
		`FROM "public"."domino_actions" ` +
		_s

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, _v...)
	}

	var _dominoAction DominoAction
	row := db.QueryRow(context.TODO(), sqlstr, _v...)
	if e := row.Scan(&_dominoAction.ID, &_dominoAction.Name, &_dominoAction.Position, &_dominoAction.RuleID, &_dominoAction.Settings); e != nil {
		if pogo.IsNoRows(e) {
			return nil, ErrDominoActionNotFound
		}
		return nil, e
	}

	return &_dominoAction, nil
}

// FindByID a `DominoAction` by some conditions.
func FindByID(db pogo.DB, id int64) (*DominoAction, error) {
	// sql select query, primary key provided by sequence
	sqlstr := `
    SELECT "id", "name", "position", "rule_id", "settings"
    FROM "public"."domino_actions"
    WHERE "id" = $1
  `

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, id)
	}

	var _dominoAction DominoAction
	row := db.QueryRow(context.TODO(), sqlstr, id)
	if e := row.Scan(&_dominoAction.ID, &_dominoAction.Name, &_dominoAction.Position, &_dominoAction.RuleID, &_dominoAction.Settings); e != nil {
		if pogo.IsNoRows(e) {
			return nil, ErrDominoActionNotFound
		}
		return nil, e
	}

	return &_dominoAction, nil
}

// FindByID a `DominoAction` by some conditions.
func (*Model) FindByID(db pogo.DB, id int64) (*DominoAction, error) {
	// sql select query, primary key provided by sequence
	sqlstr := `
    SELECT "id", "name", "position", "rule_id", "settings"
    FROM "public"."domino_actions"
    WHERE "id" = $1
  `

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, id)
	}

	var _dominoAction DominoAction
	row := db.QueryRow(context.TODO(), sqlstr, id)
	if e := row.Scan(&_dominoAction.ID, &_dominoAction.Name, &_dominoAction.Position, &_dominoAction.RuleID, &_dominoAction.Settings); e != nil {
		if pogo.IsNoRows(e) {
			return nil, ErrDominoActionNotFound
		}
		return nil, e
	}

	return &_dominoAction, nil
}

// FindByPositionAndRuleID find a dominoAction by position and rule_id
func FindByPositionAndRuleID(db pogo.DB, position int, ruleID int64) (*DominoAction, error) {
	// sql select query, primary key provided by sequence
	sqlstr := `
    SELECT "id", "name", "position", "rule_id", "settings"
    FROM "public"."domino_actions"
    WHERE "position" = $1 AND "rule_id" = $2
  `

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, position, ruleID)
	}

	var _dominoAction DominoAction
	row := db.QueryRow(context.TODO(), sqlstr, position, ruleID)
	err := row.Scan(&_dominoAction.ID, &_dominoAction.Name, &_dominoAction.Position, &_dominoAction.RuleID, &_dominoAction.Settings)
	if err != nil {
		if pogo.IsNoRows(err) {
			return nil, ErrDominoActionNotFound
		}
		return nil, err
	}

	return &_dominoAction, nil
}

// FindByPositionAndRuleID find a dominoAction by position and rule_id
func (*Model) FindByPositionAndRuleID(db pogo.DB, position int, ruleID int64) (*DominoAction, error) {
	// sql select query, primary key provided by sequence
	sqlstr := `
    SELECT "id", "name", "position", "rule_id", "settings"
    FROM "public"."domino_actions"
    WHERE "position" = $1 AND "rule_id" = $2
  `

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, position, ruleID)
	}

	var _dominoAction DominoAction
	row := db.QueryRow(context.TODO(), sqlstr, position, ruleID)
	err := row.Scan(&_dominoAction.ID, &_dominoAction.Name, &_dominoAction.Position, &_dominoAction.RuleID, &_dominoAction.Settings)
	if err != nil {
		if pogo.IsNoRows(err) {
			return nil, ErrDominoActionNotFound
		}
		return nil, err
	}
	return &_dominoAction, nil
}

// FindMany finds many "public"."domino_actions" by a condition
func FindMany(db pogo.DB, conds ...pogo.Condition) ([]*DominoAction, error) {
	dominosActions := []*DominoAction{}

	_s, _v, err := pogo.Conditions(conds...)
	if err != nil {
		return dominosActions, err
	}

	// sql select query, primary key provided by sequence
	sqlstr := `SELECT "id", "name", "position", "rule_id", "settings" ` +
		`FROM "public"."domino_actions" ` +
		_s

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, _v...)
	}

	rows, err := db.Query(context.TODO(), sqlstr, _v...)
	if err != nil {
		return dominosActions, err
	}
	defer rows.Close()

	for rows.Next() {
		var _dominoAction DominoAction
		if e := rows.Scan(&_dominoAction.ID, &_dominoAction.Name, &_dominoAction.Position, &_dominoAction.RuleID, &_dominoAction.Settings); e != nil {
			if pogo.IsNoRows(e) {
				return dominosActions, ErrDominoActionNotFound
			}
			return dominosActions, err
		}
		dominosActions = append(dominosActions, &_dominoAction)
	}
	if rows.Err() != nil {
		return dominosActions, rows.Err()
	}

	return dominosActions, nil
}

// FindMany finds many "public"."domino_actions" by a condition
func (*Model) FindMany(db pogo.DB, conds ...pogo.Condition) ([]*DominoAction, error) {
	dominosActions := []*DominoAction{}

	_s, _v, err := pogo.Conditions(conds...)
	if err != nil {
		return dominosActions, err
	}

	// sql select query, primary key provided by sequence
	sqlstr := `SELECT "id", "name", "position", "rule_id", "settings" ` +
		`FROM "public"."domino_actions" ` +
		_s

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, _v...)
	}

	rows, err := db.Query(context.TODO(), sqlstr, _v...)
	if err != nil {
		return dominosActions, err
	}
	defer rows.Close()

	for rows.Next() {
		var _dominoAction DominoAction
		if e := rows.Scan(&_dominoAction.ID, &_dominoAction.Name, &_dominoAction.Position, &_dominoAction.RuleID, &_dominoAction.Settings); e != nil {
			if pogo.IsNoRows(e) {
				return dominosActions, ErrDominoActionNotFound
			}
			return dominosActions, err
		}
		dominosActions = append(dominosActions, &_dominoAction)
	}
	if rows.Err() != nil {
		return dominosActions, rows.Err()
	}

	return dominosActions, nil
}

// Update ""public"."domino_actions"" rows in "public"."domino_actions" by a condition, returning 1 result
func Update(db pogo.DB, dominoAction *Input, conds ...pogo.Condition) (*DominoAction, error) {
	_s, _v, err := pogo.Conditions(conds...)
	if err != nil {
		return nil, err
	}

	fields := dominoAction.columns()

	// prepare the slices
	_c, _i, _v2 := slice(fields, len(_v))
	_v = append(_v, _v2...)

	// setup the update fields
	var _u []string
	for i, c := range _c {
		_u = append(_u, c+" = "+_i[i])
	}

	// return an error if no update input is provided
	if len(_u) == 0 {
		return nil, errors.New("dominoaction.Update: no input provided")
	}

	// sql query
	sqlstr := `UPDATE "public"."domino_actions" SET ` +
		strings.Join(_u, ", ") + ` ` +
		_s + ` ` +
		`RETURNING "id", "name", "position", "rule_id", "settings"`

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, _v...)
	}

	// run the query
	var _dominoAction DominoAction
	row := db.QueryRow(context.TODO(), sqlstr, _v...)
	if e := row.Scan(&_dominoAction.ID, &_dominoAction.Name, &_dominoAction.Position, &_dominoAction.RuleID, &_dominoAction.Settings); e != nil {
		if pogo.IsNoRows(e) {
			return nil, ErrDominoActionNotFound
		}
		return nil, e
	}

	return &_dominoAction, nil
}

// Update ""public"."domino_actions"" rows in "public"."domino_actions" by a condition, returning 1 result
func (*Model) Update(db pogo.DB, dominoAction *Input, conds ...pogo.Condition) (*DominoAction, error) {
	_s, _v, err := pogo.Conditions(conds...)
	if err != nil {
		return nil, err
	}

	fields := dominoAction.columns()

	// prepare the slices
	_c, _i, _v2 := slice(fields, len(_v))
	_v = append(_v, _v2...)

	// setup the update fields
	var _u []string
	for i, c := range _c {
		_u = append(_u, c+" = "+_i[i])
	}

	// return an error if no update input is provided
	if len(_u) == 0 {
		return nil, errors.New("dominoaction.Update: no input provided")
	}

	// sql query
	sqlstr := `UPDATE "public"."domino_actions" SET ` +
		strings.Join(_u, ", ") + ` ` +
		_s + ` ` +
		`RETURNING "id", "name", "position", "rule_id", "settings"`

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, _v...)
	}

	// run the query
	var _dominoAction DominoAction
	row := db.QueryRow(context.TODO(), sqlstr, _v...)
	if e := row.Scan(&_dominoAction.ID, &_dominoAction.Name, &_dominoAction.Position, &_dominoAction.RuleID, &_dominoAction.Settings); e != nil {
		if pogo.IsNoRows(e) {
			return nil, ErrDominoActionNotFound
		}
		return nil, e
	}

	return &_dominoAction, nil
}

// UpdateMany updates ""public"."domino_actions"" rows in "public"."domino_actions" by conditions, returning all results
func UpdateMany(db pogo.DB, dominoAction *Input, conds ...pogo.Condition) ([]*DominoAction, error) {
	dominosActions := []*DominoAction{}

	_s, _v, err := pogo.Conditions(conds...)
	if err != nil {
		return nil, err
	}

	fields := dominoAction.columns()

	// prepare the slices
	_c, _i, _v2 := slice(fields, len(_v))
	_v = append(_v, _v2...)

	// setup the update fields
	var _u []string
	for i, c := range _c {
		_u = append(_u, c+" = "+_i[i])
	}

	// return an error if no update input is provided
	if len(_u) == 0 {
		return nil, errors.New("dominoaction.UpdateMany: no input provided")
	}

	// sql query
	sqlstr := `UPDATE "public"."domino_actions" SET ` +
		strings.Join(_u, ", ") + ` ` +
		_s + ` ` +
		`RETURNING "id", "name", "position", "rule_id", "settings"`

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, _v...)
	}

	rows, err := db.Query(context.TODO(), sqlstr, _v...)
	if err != nil {
		return dominosActions, err
	}
	defer rows.Close()

	for rows.Next() {
		var _dominoAction DominoAction
		if e := rows.Scan(&_dominoAction.ID, &_dominoAction.Name, &_dominoAction.Position, &_dominoAction.RuleID, &_dominoAction.Settings); e != nil {
			if pogo.IsNoRows(e) {
				return dominosActions, ErrDominoActionNotFound
			}
			return dominosActions, err
		}
		dominosActions = append(dominosActions, &_dominoAction)
	}
	if rows.Err() != nil {
		return dominosActions, rows.Err()
	}

	return dominosActions, nil
}

// UpdateMany updates ""public"."domino_actions"" rows in "public"."domino_actions" by conditions, returning all results
func (*Model) UpdateMany(db pogo.DB, dominoAction *Input, conds ...pogo.Condition) ([]*DominoAction, error) {
	dominosActions := []*DominoAction{}

	_s, _v, err := pogo.Conditions(conds...)
	if err != nil {
		return nil, err
	}

	fields := dominoAction.columns()

	// prepare the slices
	_c, _i, _v2 := slice(fields, len(_v))
	_v = append(_v, _v2...)

	// setup the update fields
	var _u []string
	for i, c := range _c {
		_u = append(_u, c+" = "+_i[i])
	}

	// return an error if no update input is provided
	if len(_u) == 0 {
		return nil, errors.New("dominoaction.UpdateMany: no input provided")
	}

	// sql query
	sqlstr := `UPDATE "public"."domino_actions" SET ` +
		strings.Join(_u, ", ") + ` ` +
		_s + ` ` +
		`RETURNING "id", "name", "position", "rule_id", "settings"`

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, _v...)
	}

	rows, err := db.Query(context.TODO(), sqlstr, _v...)
	if err != nil {
		return dominosActions, err
	}
	defer rows.Close()

	for rows.Next() {
		var _dominoAction DominoAction
		if e := rows.Scan(&_dominoAction.ID, &_dominoAction.Name, &_dominoAction.Position, &_dominoAction.RuleID, &_dominoAction.Settings); e != nil {
			if pogo.IsNoRows(e) {
				return dominosActions, ErrDominoActionNotFound
			}
			return dominosActions, err
		}
		dominosActions = append(dominosActions, &_dominoAction)
	}
	if rows.Err() != nil {
		return dominosActions, rows.Err()
	}

	return dominosActions, nil
}

// UpdateByID a "dominoAction" in "public"."domino_actions" by its ""id""
func UpdateByID(db pogo.DB, id int64, dominoAction *Input) (*DominoAction, error) {
	// add values to input, overriding existing keys if present in the input
	dominoAction = dominoAction.ID(id)

	// get the columns
	fields := dominoAction.columns()

	// don't update the keys
	delete(fields, "id")

	// prepare the slices
	_c, _i, _v := slice(fields, 1)

	// setup the update fields
	var _u []string
	for i, c := range _c {
		_u = append(_u, c+" = "+_i[i])
	}

	// return an error if no update input is provided
	if len(_u) == 0 {
		return nil, errors.New("dominoaction.UpdateByID: no input provided")
	}

	// sql query
	sqlstr := `UPDATE "public"."domino_actions" SET ` +
		strings.Join(_u, ", ") + ` ` +
		`WHERE "id" = $1 ` +
		`RETURNING "id", "name", "position", "rule_id", "settings"`

	// setup the query
	values := []any{}
	values = append(values, id)
	values = append(values, _v...)

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, values...)
	}

	// run the query
	var _dominoAction DominoAction
	row := db.QueryRow(context.TODO(), sqlstr, values...)
	if e := row.Scan(&_dominoAction.ID, &_dominoAction.Name, &_dominoAction.Position, &_dominoAction.RuleID, &_dominoAction.Settings); e != nil {
		if pogo.IsNoRows(e) {
			return nil, ErrDominoActionNotFound
		}
		return nil, e
	}

	return &_dominoAction, nil
}

// UpdateByID a "dominoAction" in "public"."domino_actions" by its ""id""
func (*Model) UpdateByID(db pogo.DB, id int64, dominoAction *Input) (*DominoAction, error) {
	// add values to input, overriding existing keys if present in the input
	dominoAction = dominoAction.ID(id)

	// get the columns
	fields := dominoAction.columns()

	// don't update the keys
	delete(fields, "id")

	// prepare the slices
	_c, _i, _v := slice(fields, 1)

	// setup the update fields
	var _u []string
	for i, c := range _c {
		_u = append(_u, c+" = "+_i[i])
	}

	// return an error if no update input is provided
	if len(_u) == 0 {
		return nil, errors.New("dominoaction.UpdateByID: no input provided")
	}

	// sql query
	sqlstr := `UPDATE "public"."domino_actions" SET ` +
		strings.Join(_u, ", ") + ` ` +
		`WHERE "id" = $1 ` +
		`RETURNING "id", "name", "position", "rule_id", "settings"`

	// setup the query
	values := []any{}
	values = append(values, id)
	values = append(values, _v...)

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, values...)
	}

	// run the query
	var _dominoAction DominoAction
	row := db.QueryRow(context.TODO(), sqlstr, values...)
	if e := row.Scan(&_dominoAction.ID, &_dominoAction.Name, &_dominoAction.Position, &_dominoAction.RuleID, &_dominoAction.Settings); e != nil {
		if pogo.IsNoRows(e) {
			return nil, ErrDominoActionNotFound
		}
		return nil, e
	}

	return &_dominoAction, nil
}

// UpdateByPositionAndRuleID find a DominoAction
func UpdateByPositionAndRuleID(db pogo.DB, position int, ruleID int64, dominoAction *Input) (*DominoAction, error) {
	// add values to input, overriding existing keys if present in the input
	dominoAction = dominoAction.Position(position).RuleID(ruleID)

	// get the columns
	fields := dominoAction.columns()

	// don't update the keys
	delete(fields, "position")
	delete(fields, "rule_id")

	// prepare the slices
	_c, _i, _v := slice(fields, 2)

	// setup the update fields
	var _u []string
	for i, c := range _c {
		_u = append(_u, c+" = "+_i[i])
	}

	// return an error if no update input is provided
	if len(_u) == 0 {
		return nil, errors.New("dominoaction.UpdateByPositionAndRuleID: no input provided")
	}

	// sql query
	sqlstr := `UPDATE "public"."domino_actions" SET ` +
		strings.Join(_u, ", ") + ` ` +
		`WHERE "position" = $1 AND "rule_id" = $2 ` +
		`RETURNING "id", "name", "position", "rule_id", "settings"`

	// setup the query
	values := []any{}
	values = append(values, position)
	values = append(values, ruleID)
	values = append(values, _v...)

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, values...)
	}

	// run the query
	var _dominoAction DominoAction
	row := db.QueryRow(context.TODO(), sqlstr, values...)
	if e := row.Scan(&_dominoAction.ID, &_dominoAction.Name, &_dominoAction.Position, &_dominoAction.RuleID, &_dominoAction.Settings); e != nil {
		if pogo.IsNoRows(e) {
			return nil, ErrDominoActionNotFound
		}
		return nil, e
	}

	return &_dominoAction, nil
}

// UpdateByPositionAndRuleID find a DominoAction
func (*Model) UpdateByPositionAndRuleID(db pogo.DB, position int, ruleID int64, dominoAction *Input) (*DominoAction, error) {
	// add values to input, overriding existing keys if present in the input
	dominoAction = dominoAction.Position(position).RuleID(ruleID)

	// get the columns
	fields := dominoAction.columns()

	// don't update the keys
	delete(fields, "position")
	delete(fields, "rule_id")

	// prepare the slices
	_c, _i, _v := slice(fields, 2)

	// setup the update fields
	var _u []string
	for i, c := range _c {
		_u = append(_u, c+" = "+_i[i])
	}

	// return an error if no update input is provided
	if len(_u) == 0 {
		return nil, errors.New("dominoaction.UpdateByPositionAndRuleID: no input provided")
	}

	// sql query
	sqlstr := `UPDATE "public"."domino_actions" SET ` +
		strings.Join(_u, ", ") + ` ` +
		`WHERE "position" = $1 AND "rule_id" = $2 ` +
		`RETURNING "id", "name", "position", "rule_id", "settings"`

	// setup the query
	values := []any{}
	values = append(values, position)
	values = append(values, ruleID)
	values = append(values, _v...)

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, values...)
	}

	// run the query
	var _dominoAction DominoAction
	row := db.QueryRow(context.TODO(), sqlstr, values...)
	if e := row.Scan(&_dominoAction.ID, &_dominoAction.Name, &_dominoAction.Position, &_dominoAction.RuleID, &_dominoAction.Settings); e != nil {
		if pogo.IsNoRows(e) {
			return nil, ErrDominoActionNotFound
		}
		return nil, e
	}

	return &_dominoAction, nil
}

// Delete `DominoAction`s by some conditions. Returns the first result.
// Warning: This can delete more than 1 row
func Delete(db pogo.DB, conds ...pogo.Condition) (*DominoAction, error) {
	_s, _v, err := pogo.Conditions(conds...)
	if err != nil {
		return nil, err
	}

	// sql delete query
	sqlstr := `DELETE FROM "public"."domino_actions" ` +
		_s + ` ` +
		`RETURNING "id", "name", "position", "rule_id", "settings"`

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, _v...)
	}

	var _dominoAction DominoAction
	row := db.QueryRow(context.TODO(), sqlstr, _v...)
	if e := row.Scan(&_dominoAction.ID, &_dominoAction.Name, &_dominoAction.Position, &_dominoAction.RuleID, &_dominoAction.Settings); e != nil {
		if pogo.IsNoRows(e) {
			return nil, ErrDominoActionNotFound
		}
		return nil, e
	}

	return &_dominoAction, nil
}

// Delete `DominoAction`s by some conditions. Returns the first result.
// Warning: This can delete more than 1 row
func (*Model) Delete(db pogo.DB, conds ...pogo.Condition) (*DominoAction, error) {
	_s, _v, err := pogo.Conditions(conds...)
	if err != nil {
		return nil, err
	}

	// sql delete query
	sqlstr := `DELETE FROM "public"."domino_actions" ` +
		_s + ` ` +
		`RETURNING "id", "name", "position", "rule_id", "settings"`

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, _v...)
	}

	var _dominoAction DominoAction
	row := db.QueryRow(context.TODO(), sqlstr, _v...)
	if e := row.Scan(&_dominoAction.ID, &_dominoAction.Name, &_dominoAction.Position, &_dominoAction.RuleID, &_dominoAction.Settings); e != nil {
		if pogo.IsNoRows(e) {
			return nil, ErrDominoActionNotFound
		}
		return nil, e
	}

	return &_dominoAction, nil
}

// DeleteMany `DominoAction`s by some conditions, returning all results.
func DeleteMany(db pogo.DB, conds ...pogo.Condition) ([]*DominoAction, error) {
	dominosActions := []*DominoAction{}

	_s, _v, err := pogo.Conditions(conds...)
	if err != nil {
		return dominosActions, err
	}

	// sql delete query
	sqlstr := `DELETE FROM "public"."domino_actions" ` +
		_s + ` ` +
		`RETURNING "id", "name", "position", "rule_id", "settings"`

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, _v...)
	}

	rows, err := db.Query(context.TODO(), sqlstr, _v...)
	if err != nil {
		return dominosActions, err
	}
	defer rows.Close()

	for rows.Next() {
		var _dominoAction DominoAction
		if e := rows.Scan(&_dominoAction.ID, &_dominoAction.Name, &_dominoAction.Position, &_dominoAction.RuleID, &_dominoAction.Settings); e != nil {
			if pogo.IsNoRows(e) {
				return dominosActions, ErrDominoActionNotFound
			}
			return dominosActions, err
		}
		dominosActions = append(dominosActions, &_dominoAction)
	}
	if rows.Err() != nil {
		return dominosActions, rows.Err()
	}

	return dominosActions, nil
}

// DeleteMany `DominoAction`s by some conditions, returning all results.
func (*Model) DeleteMany(db pogo.DB, conds ...pogo.Condition) ([]*DominoAction, error) {
	dominosActions := []*DominoAction{}

	_s, _v, err := pogo.Conditions(conds...)
	if err != nil {
		return dominosActions, err
	}

	// sql delete query
	sqlstr := `DELETE FROM "public"."domino_actions" ` +
		_s + ` ` +
		`RETURNING "id", "name", "position", "rule_id", "settings"`

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, _v...)
	}

	rows, err := db.Query(context.TODO(), sqlstr, _v...)
	if err != nil {
		return dominosActions, err
	}
	defer rows.Close()

	for rows.Next() {
		var _dominoAction DominoAction
		if e := rows.Scan(&_dominoAction.ID, &_dominoAction.Name, &_dominoAction.Position, &_dominoAction.RuleID, &_dominoAction.Settings); e != nil {
			if pogo.IsNoRows(e) {
				return dominosActions, ErrDominoActionNotFound
			}
			return dominosActions, err
		}
		dominosActions = append(dominosActions, &_dominoAction)
	}
	if rows.Err() != nil {
		return dominosActions, rows.Err()
	}

	return dominosActions, nil
}

// DeleteByID deletes a "dominoAction"
func DeleteByID(db pogo.DB, id int64) (*DominoAction, error) {
	// sql delete query
	sqlstr := `DELETE FROM "public"."domino_actions" ` +
		`WHERE "id" = $1 ` +
		`RETURNING "id", "name", "position", "rule_id", "settings"`

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, id)
	}

	// run the query
	var _dominoAction DominoAction
	row := db.QueryRow(context.TODO(), sqlstr, id)
	if e := row.Scan(&_dominoAction.ID, &_dominoAction.Name, &_dominoAction.Position, &_dominoAction.RuleID, &_dominoAction.Settings); e != nil {
		if pogo.IsNoRows(e) {
			return nil, ErrDominoActionNotFound
		}
		return nil, e
	}

	return &_dominoAction, nil
}

// DeleteByID deletes a "dominoAction"
func (*Model) DeleteByID(db pogo.DB, id int64) (*DominoAction, error) {
	// sql delete query
	sqlstr := `DELETE FROM "public"."domino_actions" ` +
		`WHERE "id" = $1 ` +
		`RETURNING "id", "name", "position", "rule_id", "settings"`

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, id)
	}

	// run the query
	var _dominoAction DominoAction
	row := db.QueryRow(context.TODO(), sqlstr, id)
	if e := row.Scan(&_dominoAction.ID, &_dominoAction.Name, &_dominoAction.Position, &_dominoAction.RuleID, &_dominoAction.Settings); e != nil {
		if pogo.IsNoRows(e) {
			return nil, ErrDominoActionNotFound
		}
		return nil, e
	}

	return &_dominoAction, nil
}

// DeleteByPositionAndRuleID deletes a "dominoAction"
func DeleteByPositionAndRuleID(db pogo.DB, position int, ruleID int64) (*DominoAction, error) {
	// sql delete query
	sqlstr := `DELETE FROM "public"."domino_actions" ` +
		`WHERE "position" = $1 AND "rule_id" = $2 ` +
		`RETURNING "id", "name", "position", "rule_id", "settings"`

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, position, ruleID)
	}

	// run the query
	var _dominoAction DominoAction
	row := db.QueryRow(context.TODO(), sqlstr, position, ruleID)
	if e := row.Scan(&_dominoAction.ID, &_dominoAction.Name, &_dominoAction.Position, &_dominoAction.RuleID, &_dominoAction.Settings); e != nil {
		if pogo.IsNoRows(e) {
			return nil, ErrDominoActionNotFound
		}
		return nil, e
	}

	return &_dominoAction, nil
}

// DeleteByPositionAndRuleID deletes a "dominoAction"
func (*Model) DeleteByPositionAndRuleID(db pogo.DB, position int, ruleID int64) (*DominoAction, error) {
	// sql delete query
	sqlstr := `DELETE FROM "public"."domino_actions" ` +
		`WHERE "position" = $1 AND "rule_id" = $2 ` +
		`RETURNING "id", "name", "position", "rule_id", "settings"`

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, position, ruleID)
	}

	// run the query
	var _dominoAction DominoAction
	row := db.QueryRow(context.TODO(), sqlstr, position, ruleID)
	if e := row.Scan(&_dominoAction.ID, &_dominoAction.Name, &_dominoAction.Position, &_dominoAction.RuleID, &_dominoAction.Settings); e != nil {
		if pogo.IsNoRows(e) {
			return nil, ErrDominoActionNotFound
		}
		return nil, e
	}

	return &_dominoAction, nil
}

// Upsert inserts a `"public"."domino_actions"`, updating the row if `"id"` already exists.
func Upsert(db pogo.DB, dominoAction *Input) (*DominoAction, error) {
	// get all the non-nil columns and prepare them for the query
	_c, _i, _v := slice(dominoAction.columns(), 0)

	// setup the update fields
	var _u []string
	for _, c := range _c {
		_u = append(_u, c+" = excluded."+c)
	}

	// sql query
	sqlstr := `INSERT INTO "public"."domino_actions" (` + strings.Join(_c, ", ") + `) ` +
		`VALUES (` + strings.Join(_i, ", ") + `) ` +
		`ON CONFLICT ("id") ` +
		`DO UPDATE SET ` + strings.Join(_u, ", ") + ` ` +
		`RETURNING "id", "name", "position", "rule_id", "settings"`

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, _v...)
	}

	// run query
	var _dominoAction DominoAction
	row := db.QueryRow(context.TODO(), sqlstr, _v...)
	if e := row.Scan(&_dominoAction.ID, &_dominoAction.Name, &_dominoAction.Position, &_dominoAction.RuleID, &_dominoAction.Settings); e != nil && !pogo.IsNoRows(e) {
		return nil, e
	}

	return &_dominoAction, nil
}

// Upsert inserts a `"public"."domino_actions"`, updating the row if `"id"` already exists.
func (*Model) Upsert(db pogo.DB, dominoAction *Input) (*DominoAction, error) {
	// get all the non-nil columns and prepare them for the query
	_c, _i, _v := slice(dominoAction.columns(), 0)

	// setup the update fields
	var _u []string
	for _, c := range _c {
		_u = append(_u, c+" = excluded."+c)
	}

	// sql query
	sqlstr := `INSERT INTO "public"."domino_actions" (` + strings.Join(_c, ", ") + `) ` +
		`VALUES (` + strings.Join(_i, ", ") + `) ` +
		`ON CONFLICT ("id") ` +
		`DO UPDATE SET ` + strings.Join(_u, ", ") + ` ` +
		`RETURNING "id", "name", "position", "rule_id", "settings"`

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, _v...)
	}

	// run query
	var _dominoAction DominoAction
	row := db.QueryRow(context.TODO(), sqlstr, _v...)
	if e := row.Scan(&_dominoAction.ID, &_dominoAction.Name, &_dominoAction.Position, &_dominoAction.RuleID, &_dominoAction.Settings); e != nil && !pogo.IsNoRows(e) {
		return nil, e
	}

	return &_dominoAction, nil
}

// UpsertByID inserts a `"public"."domino_actions"`, updating the row if `"id"` already exists.
func UpsertByID(db pogo.DB, id int64, dominoAction *Input) (*DominoAction, error) {
	// add values to input, overriding existing keys if present in the input
	dominoAction = dominoAction.ID(id)

	// get all the non-nil columns and prepare them for the query
	_c, _i, _v := slice(dominoAction.columns(), 0)

	// setup the update fields
	var _u []string
	for _, c := range _c {
		_u = append(_u, c+" = excluded."+c)
	}

	// sql query
	sqlstr := `INSERT INTO "public"."domino_actions" (` + strings.Join(_c, ", ") + `) ` +
		`VALUES (` + strings.Join(_i, ", ") + `) ` +
		`ON CONFLICT ("id") ` +
		`DO UPDATE SET ` + strings.Join(_u, ", ") + ` ` +
		`RETURNING "id", "name", "position", "rule_id", "settings"`

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, _v...)
	}

	// run query
	var _dominoAction DominoAction
	row := db.QueryRow(context.TODO(), sqlstr, _v...)
	if e := row.Scan(&_dominoAction.ID, &_dominoAction.Name, &_dominoAction.Position, &_dominoAction.RuleID, &_dominoAction.Settings); e != nil && !pogo.IsNoRows(e) {
		return nil, e
	}

	return &_dominoAction, nil
}

// UpsertByID inserts a `"public"."domino_actions"`, updating the row if `"id"` already exists.
func (*Model) UpsertByID(db pogo.DB, id int64, dominoAction *Input) (*DominoAction, error) {
	// add values to input, overriding existing keys if present in the input
	dominoAction = dominoAction.ID(id)

	// get all the non-nil columns and prepare them for the query
	_c, _i, _v := slice(dominoAction.columns(), 0)

	// setup the update fields
	var _u []string
	for _, c := range _c {
		_u = append(_u, c+" = excluded."+c)
	}

	// sql query
	sqlstr := `INSERT INTO "public"."domino_actions" (` + strings.Join(_c, ", ") + `) ` +
		`VALUES (` + strings.Join(_i, ", ") + `) ` +
		`ON CONFLICT ("id") ` +
		`DO UPDATE SET ` + strings.Join(_u, ", ") + ` ` +
		`RETURNING "id", "name", "position", "rule_id", "settings"`

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, _v...)
	}

	// run query
	var _dominoAction DominoAction
	row := db.QueryRow(context.TODO(), sqlstr, _v...)
	if e := row.Scan(&_dominoAction.ID, &_dominoAction.Name, &_dominoAction.Position, &_dominoAction.RuleID, &_dominoAction.Settings); e != nil && !pogo.IsNoRows(e) {
		return nil, e
	}

	return &_dominoAction, nil
}

// UpsertByPositionAndRuleID inserts a `"public"."domino_actions"`, updating the row if `"position", "rule_id"` already exists.
func UpsertByPositionAndRuleID(db pogo.DB, position int, ruleID int64, dominoAction *Input) (*DominoAction, error) {
	// add values to input, overriding existing keys if present in the input
	dominoAction = dominoAction.Position(position).RuleID(ruleID)

	// get all the non-nil columns and prepare them for the query
	_c, _i, _v := slice(dominoAction.columns(), 0)

	// setup the update fields
	var _u []string
	for _, c := range _c {
		_u = append(_u, c+" = excluded."+c)
	}

	// sql query
	sqlstr := `INSERT INTO "public"."domino_actions" (` + strings.Join(_c, ", ") + `) ` +
		`VALUES (` + strings.Join(_i, ", ") + `) ` +
		`ON CONFLICT ("position", "rule_id") ` +
		`DO UPDATE SET ` + strings.Join(_u, ", ") + ` ` +
		`RETURNING "id", "name", "position", "rule_id", "settings"`

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, _v...)
	}

	// run query
	var _dominoAction DominoAction
	row := db.QueryRow(context.TODO(), sqlstr, _v...)
	if e := row.Scan(&_dominoAction.ID, &_dominoAction.Name, &_dominoAction.Position, &_dominoAction.RuleID, &_dominoAction.Settings); e != nil && !pogo.IsNoRows(e) {
		return nil, e
	}

	return &_dominoAction, nil
}

// UpsertByPositionAndRuleID inserts a `"public"."domino_actions"`, updating the row if `"position", "rule_id"` already exists.
func (*Model) UpsertByPositionAndRuleID(db pogo.DB, position int, ruleID int64, dominoAction *Input) (*DominoAction, error) {
	// add values to input, overriding existing keys if present in the input
	dominoAction = dominoAction.Position(position).RuleID(ruleID)

	// get all the non-nil columns and prepare them for the query
	_c, _i, _v := slice(dominoAction.columns(), 0)

	// setup the update fields
	var _u []string
	for _, c := range _c {
		_u = append(_u, c+" = excluded."+c)
	}

	// sql query
	sqlstr := `INSERT INTO "public"."domino_actions" (` + strings.Join(_c, ", ") + `) ` +
		`VALUES (` + strings.Join(_i, ", ") + `) ` +
		`ON CONFLICT ("position", "rule_id") ` +
		`DO UPDATE SET ` + strings.Join(_u, ", ") + ` ` +
		`RETURNING "id", "name", "position", "rule_id", "settings"`

	// log query if we've provided a logger
	if pogo.Log != nil {
		pogo.Log(sqlstr, _v...)
	}

	// run query
	var _dominoAction DominoAction
	row := db.QueryRow(context.TODO(), sqlstr, _v...)
	if e := row.Scan(&_dominoAction.ID, &_dominoAction.Name, &_dominoAction.Position, &_dominoAction.RuleID, &_dominoAction.Settings); e != nil && !pogo.IsNoRows(e) {
		return nil, e
	}

	return &_dominoAction, nil
}

// slice converts our columns into something the sql driver can understand
func slice(columns map[string]any, offset int) (c []string, i []string, v []any) {
	n := offset + 1
	for col, val := range columns {
		c = append(c, strconv.Quote(col))
		i = append(i, "$"+strconv.Itoa(n))
		v = append(v, val)
		n++
	}
	return c, i, v
}
